### ISSUE TITLE
macos下无法加载插件

### ISSUE THREAD

**Issue by wilbyang** [wangfenjin/simple#100]
libsimple.dylib” cannot be opened because the developer cannot be verified.

**Comment by wangfenjin** [comment]
暂时可以考虑通过下面的方式解决，或者自己编译

There are two tips I used to solve the Jackett malware popup issue. 
 
### 1) Quarantine removal
**The first tip is to remove quarantine flag in a recursive manner for your intended folder:**

```shell
$ sudo xattr -r -d com.apple.quarantine /path/to/folder
```
In this case for Jackett use: 
```Shell
$ sudo xattr -r -d com.apple.quarantine /path/to/Jackett
```
The command will recursively delete the extended attribute (xattr) of com.apple.quarantine attribute recursively to the files in the folder. 

The (-r) option will allow the quarantine attribute of all files inside the application to be selected, while the (-d) deletes the extended attribute name.

You can find more information in the extended attributes (xattr) help page:
```shell
$ xattr -h
```

### 2) Terminal "Privacy"
**The second tip is setting the Terminal "privacy".**

System Preferences -> Security & Privacy -> Privacy  and select "Developer Tools" on the left, and add terminal to allow.

This step allows the Terminal app to run software locally that does not meet the system's security policy.

![terminal privacy][logo]

[logo]: https://user-images.githubusercontent.com/306284/71833879-cfaa4100-30a5-11ea-8c84-6254ee4cb6ab.png "terminal privacy"

**Apple Support Reference:**

Safely open apps on your Mac

[https://support.apple.com/en-us/HT202491](https://support.apple.com/en-us/HT202491)

_Originally posted by @donfrancisco in https://github.com/Jackett/Jackett/issues/5589#issuecomment-571222585_

**Comment by wangfenjin** [comment]
后面我可能会参考 https://github.com/Jackett/Jackett/pull/8915 做个修改

**Comment by wilbyang** [comment]
@wangfenjin trick #1 works, great thanks!
