### ISSUE TITLE
从后往前匹配失败

### ISSUE THREAD

**Issue by DuWen** [wangfenjin/simple#101]
你好，在使用simple时，遇到了个问题，如下：
示例：aaaaamm
关键字：mm
结果：0

期待你的回复，thanks

**Comment by wangfenjin** [comment]
因为英文是按照前缀匹配，所以搜后缀搜不到

**Comment by wangfenjin** [comment]
https://www.wangfenjin.com/posts/simple-tokenizer/

具体的搜索规则参见这里，理论上这是大家普遍接受的方式

**Comment by DuWen** [comment]
好的 谢谢啦
