### ISSUE TITLE
windows下编译出来的解析中文时会崩溃

### ISSUE THREAD

**Issue by tonyzzp** [wangfenjin/simple#104]
自己使用cmake编译的。

```
mkdir build
cd build
cmake ..
cmake --build .
```

插件可以加载成功，但只要遇到中文内容就会崩溃。

```
d:\github\simple\test_windows>sqlite3
SQLite version 3.32.3 2020-06-18 14:00:33
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .load simple
sqlite> select simple_query('ni hao');
( n+i* OR ni* ) AND ( h+a+o* OR ha+o* OR hao* )
sqlite> select simple_query('你好');
```

执行到这里就会崩溃，错误大概是  

Debug Assertion Failed

sqlite3.exe    minkernel/ctrs/ucrt/appcrt/convert/isctype.cpp  36行

c>=-1 && c<=255 。

我在wsl下编译过，全部正常。

**Comment by tonyzzp** [comment]
用ninja编译成功了，也许是vs studio版本的问题？ 2022版的。懒得深究了。

**Comment by wangfenjin** [comment]
`minkernel/ctrs/ucrt/appcrt/convert/isctype.cpp 36行` 这个开起来不是我的文件，应该是哪个系统依赖的文件有问题

如果没啥问题了可以把 issue 关掉
