### ISSUE TITLE
simple_highlight_pos 内容有空格时候返回值不对

### ISSUE THREAD

**Issue by jiangyiyon** [wangfenjin/simple#109]
你好，报一个关于simple_highlight_pos的bug，我一个文本内容中间有空格，eg:宝宝 宝贝 孩子 小孩,自拍,漫画, 我match的字是 孩， simple_highlight_pos返回. 4,5;7,8;   pos 没有加上空格，

**Comment by wangfenjin** [comment]
嗯，确实改成返回字节数下标比较合理
