### ISSUE TITLE
插件加载的时机？

### ISSUE THREAD

**Issue by xi-mad** [wangfenjin/simple#112]
当每次使用命令行工具连接sqlite的时候，可以`.load xxx`，

如果我在一个web应用中使用，我是否应该在每个开启的session中都先加载这个插件？

**Comment by wangfenjin** [comment]
不知道你用的什么代码，你看看 API 是什么调用的，没用过就要调用

**Comment by xi-mad** [comment]
`    @PostConstruct
    public void init(){
        searchMapper.load(path);
        log.info("load simple extension success");
    }

    @Update("select load_extension('${path}')")
    void load(String path);
`

Java中这样写可以，构造函数执行完之后加载插件，
jdbcurl: jdbc:sqlite:data/dbs/xx.db?date_string_format=yyyy-MM-dd HH:mm:ss&enable_load_extension=true
jdbcurl上要加上enable_load_extension=true，不然会报错说没有权限

**Comment by xi-mad** [comment]
![image](https://user-images.githubusercontent.com/26453680/216496490-b5fae642-11c6-4081-8d2d-8eeae98d4f6a.png)
spring中这样来做更合适一些，
