### ISSUE TITLE
windows下go的example运行报错： error during initialization:

### ISSUE THREAD

**Issue by mjiulee** [wangfenjin/simple#113]
首先感谢大佬提供这很实用的库~ 我在windows10环境，编译过程顺利，也成功编译了dll，通过SQLiteStudio.可视化工具加载dll，并做了简单测试，搜索功能都正常。

但是使用go语言的example加载dll后，执行查询的时候，报error during initialization错，我自己排查了下，发现报错是在：github.com/mattn/go-sqlite3库里面：
![企业微信截图_16777213503580](https://user-images.githubusercontent.com/742968/222612441-32128611-43a0-4aca-8532-ae127c535c36.png)

[类似问题参考：](https://github.com/mattn/go-sqlite3/issues/1066)

我的具体代码如下，希望大佬给点建议，看到底错在哪了，怎么调整。
```
 func main() {
	sql.Register("sqlite3_simple",
		&sqlite3.SQLiteDriver{
			Extensions: []string{
				"simple",
			},
		}) 
	db, err := sql.Open("sqlite3_simple", "cc.db")
	if err != nil {
		log.Fatal("open error: ", err)
	}
	defer db.Close()
        //此处建表过程，已经通过工具创建，不再通过代码创建表和对应的触发器
        rows, err := db.Query(`SELECT * FROM news_fts`)
	if err != nil {
		log.Fatal("query error: ", err)
	}
	defer rows.Close()

	for rows.Next() {
		var query string
		rows.Scan(&query)
		fmt.Printf("%s\n", query)
	}
}
```

**Comment by wangfenjin** [comment]
zErrmsg 是啥？

https://github.com/wangfenjin/simple/blob/master/examples/go/main.go

我这里写了一个 go 的例子，如果有问题，大概率是你本机的 sqlite 库不支持 fts

**Comment by mjiulee** [comment]
我又折腾了下，go run 的时候，加入 --tags "fts5" 参数，
然后，下面的查询执行成功，数据也正确：
```
`SELECT * FROM news_fts`
```

但是下面的查询出来为空，但是库里面是有数据的
````
rows, err := db.Query(`SELECT * FROM news_fts WHERE title MATCH simple_query('?')`, "数字中国")
````

是我go执行都编译参数漏了啥么？

**Comment by mjiulee** [comment]
发现问题了，我的低级错误 
是这里simple_query('?')，多了问号，要改为：simple_query(?)
还是非常感谢~~
