### ISSUE TITLE
“找不到指定模块 ”错误

### ISSUE THREAD

**Issue by mjiulee** [wangfenjin/simple#116]
编译成exe后，分发给用户，部分用户pc上会报错：“找不到指定模块 ”
对比发现，都是win10系统，报错的系统版本号较旧【不确定是这个问题导致，还在查】

请教下，有没有什么方式，编译一次就能使用多个版本的win10系统的？

**Comment by wangfenjin** [comment]
看起来要么是他的 sqlite 不支持 fts，要么是他没有把编译的分词插件目录设置好？

**Comment by wangfenjin** [comment]
我没有windows电脑，很难帮你debug；你可以在有问题的电脑上通过sqlite命令行，参考 example.sql 加载插件看看问题

**Comment by mjiulee** [comment]
我找了台机器，重新编译了simple，就可以了。
但是这样就有个问题，我不知道用户的win系统版本号是怎么样的。
有没有什么办法规避这种问题？

**Comment by ggymm** [comment]
这个问题我也遇到过，我在win11下编译的库，在win10上也会报找不到模块的错误

**Comment by lu972166094** [comment]
> 这个问题我也遇到过，我在win11下编译的库，在win10上也会报找不到模块的错误

你是怎么编译的呀，我用visual studio 2022编译，总是编译出x86的包

**Comment by AndySpider** [comment]
找不到指定模块有可能是因为某些windows上缺少VC库导致的，比如MSVCP**.dll, VCRUNTIME**.dll等，可以用dependencies工具看下simple.dll在当前系统下是不是缺少依赖库。
解决办法就是安装微软提供的vc_redist程序，https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
