### ISSUE TITLE
虚拟表字段声明UNINDEXED,会增加存储空间吗?

### ISSUE THREAD

**Issue by springrain** [wangfenjin/simple#117]
我目前是原始表+虚拟表,通过触发器进行同步数据,遇到查询就是嵌套in查询
例如:```select * from demo where id in (select id from demo_fts where demo_fts  match  jieba_query('中华国歌') )```
如果我把其他字段也都在虚拟表放到虚拟表demo_fts里,声明为UNINDEXED,这样fts是引用原表数据,还是会复制一份放到虚拟表,只是不分词索引了?

还有一个问题:就是禁用了拼音 tokenize = 'simple 0',这个时候分词器是jieba吗? 如果不是,应该怎么把分词器设置为jieba?

非常感谢大佬无私开源的项目

**Comment by wangfenjin** [comment]
第一个问题：

* 对于 [unindex](https://www.sqlite.org/fts5.html#the_unindexed_column_option) 的问题，他决定的是是否对这一列数据做索引，如果是 unindex 那么就是不做索引，它只决定索引文件的大小（不做索引当然文件就小一些）
* 但是我感觉你的问题是 fts 表会不会把原数据 copy 一份，这个跟 unindex 没关系，因为 unindex 只是关注索引。原表数据会不会 copy 是由 [content](https://www.sqlite.org/fts5.html#external_content_and_contentless_tables) 的配置决定的，如果你不想 copy 就用 contentless 或者 external content 表。
* 看你的 sql 用 contentless 表就行了，因为你只用到了 rowid。如果你想直接从 fts 表读出来数据并且不 copy 一遍，那就用 external content 表

第二个问题：

* tokenize = 'simple 0' 指的是在建索引的时候要不要建拼音索引，比如你插入一个 “中” 字，要不要把 “中” 字的拼音比如 "zhong" 也插入进去。因为只有把 "zhong" 放到索引里面，你才能用 "zhong" 搜索到 "中" 字。0 表示建拼音的索引。这个是建索引的过程，插入的时候做的。
* 至于 jieba ， 是查询的时候做的，跟是否使用拼音没关系。比如你查询的时候搜索 “中国”，如果是用 simple_query，那么它会把“中国人” 拆成 "中" 和 “国” 来查询，这时候 “中华人民共和国” 会命中，单字命中；但是如果你用 jieba_query，它会把 “中国” 拆成 “中国”，这时候 “中华人民共和国” **不会**命中，因为 中国 两个字不连在一起。一般来说查询中文用 jieba_query 效果会好一些。
* 注意到上面不管是 simple_query 还是 jieba_query 都和拼音没啥关系，你输入中文他不会把中文转成拼音去查，不然你查 “中” 可能就会命中 “钟” 或者 “终”，这就很奇怪了。但是如果你建了拼音索引，查 "zhong" 就会命中 ”中“ “钟” 或者 “终”。

要把查询过程和建索引过程分开看，分别弄清楚

**Comment by springrain** [comment]
非常感谢大佬, 
1.我目前使用的是 external content,查询里既有全文检索匹配,也有普通字段值相等,
```select * from demo where id in (select id from demo_fts where demo_fts  match  jieba_query('中华国歌') ) and name='demo' ```
但是实际我看,fts虚拟表也可以做普通的条件查询,说是性能会降低,就是可以把所有字段都在虚拟表里映射对应,语句就是
```select * from demo_fts where demo_fts  match  jieba_query('中华国歌') and  name='demo' ```
我也没测试性能差距多大,目前是按照普通表和虚拟表混合用的.

2.第二个问题是因为创建索引的时候应该是和分词器相关的,比如 同样的内容,不同的分词器就会产生不同的索引,所以我主要是想问下,simple创建索引的时候,可以指定使用jieba的分词器吗?这样查询使用jieba_query,理论上准确率会更高些

再次感谢大佬

**Comment by springrain** [comment]
> 第二个问题，可以；建索引流程是一样的，查询既可以使用simple也可以使用jieba
大佬,现在已经实现jieba分词创建的索引吗? 还是以后会实现呀?

**Comment by wangfenjin** [comment]
哥，我解释已经很清楚了啊，建索引跟jieba没关系，simple 建的索引既可以用simple_query查也可以用 jieba_query查

**Comment by springrain** [comment]
好的,多谢大佬
