### ISSUE TITLE
Go Example运行问题

### ISSUE THREAD

**Issue by Halimao** [wangfenjin/simple#119]
go语言版本的Example运行后提示以下错误:
`2023/05/16 10:47:02 query error: libsimple-osx-x64/libsimple.so: cannot open shared object file: No such file or directory`

解压后的libsimple-osx-x64目录确实没有这个libsimple.so这个文件。另外
`wget -qO- https://github.com/wangfenjin/simple/releases/download/v0.1.0/libsimple-osx-x64.zip | tar xf -`
也会由于压缩包格式问题无法使用tar解压

**Comment by wangfenjin** [comment]
是无法解压还是解压后没这个文件；无法解压的话是不是你没安装 tar 命令

**Comment by Halimao** [comment]
> 是无法解压还是解压后没这个文件；无法解压的话是不是你没安装 tar 命令

两个问题：
1、压缩包由于格式问题，tar无法解压
2、使用unzip解压压缩文件后，找不到libsimple.so文件

**Comment by wangfenjin** [comment]
可以吧 run.sh 的链接换成最新版的试下

**Comment by Halimao** [comment]
> 可以吧 run.sh 的链接换成最新版的试下

确认个事情,代码里面
`sql.Register("sqlite3_simple", &sqlite3.SQLiteDriver{
	Extensions: []string{
		"libsimple-osx-x64/libsimple",
	},
})`
这个路径能变吗，我用的wsl2，这些要下载哪个
![image](https://github.com/wangfenjin/simple/assets/25278203/01aac1a8-653c-42e2-863b-395bfc916e30)

**Comment by Halimao** [comment]
> 

使用 `https://github.com/wangfenjin/simple/releases/download/v0.2.2/libsimple-linux-ubuntu-latest.zip` ，这个包里面有libsimple.so文件。
运行 `go build --tags fts5 -o gosimple && ./gosimple` 成功输出 `( p+i+n+y+i+n* OR pin+yi+n* OR pin+yin* OR pinyin* )`

感谢作者大大^_^
