### ISSUE TITLE
在electron上引入的时候，在几个用户电脑上会报DevTools was disconnected from the page. 

### ISSUE THREAD

**Issue by linxuda** [wangfenjin/simple#121]
在electron上引入的时候，在几个用户电脑上控制台会报DevTools was disconnected from the page.  经排查基本可以断定是加载dll的时候被系统权限拦截了，我想知道加载dll的时候需要哪些权限

**Comment by wangfenjin** [comment]
不引入 dll 就不报错吗？这方面我不太懂，没法帮到你

https://github.com/TryGhost/node-sqlite3/issues/1504#issuecomment-1099908912

**Comment by linxuda** [comment]
> 不引入 dll 就不报错吗？这方面我不太懂，没法帮到你
> 
> [TryGhost/node-sqlite3#1504 (comment)](https://github.com/TryGhost/node-sqlite3/issues/1504#issuecomment-1099908912)

是的，不做前端搜索的功能程序就是正常的

**Comment by wangfenjin** [comment]
https://stackoverflow.com/a/71857996/1203241 看起来是可以用的

是必现错误还是偶发的？可能跟具体机器的设置相关，我这边也不太懂

**Comment by linxuda** [comment]
> https://stackoverflow.com/a/71857996/1203241 看起来是可以用的
> 
> 是必现错误还是偶发的？可能跟具体机器的设置相关，我这边也不太懂

在几台机器上是必现的，大多数电脑是可用的，目前还没找到是什么原因引起的

**Comment by linxuda** [comment]
这个问题已经解决了，是因为程序的目录缺少一个依赖文件
