### ISSUE TITLE
请问有arm64的插件包吗

### ISSUE THREAD

**Issue by linxuda** [wangfenjin/simple#122]

**Comment by wangfenjin** [comment]
不知道 github action 支不支持 arm 的机器，现在没有需要你自己编译

**Comment by linxuda** [comment]
可以提供一个生成arm动态库的工程的脚本吗

**Comment by linxuda** [comment]
> 不知道 github action 支不支持 arm 的机器，现在没有需要你自己编译
可以提供一下哪里有编译的教程吗？我不太懂这些。。。

**Comment by wangfenjin** [comment]
不好意思回复晚了，之前有点忙

https://github.com/wangfenjin/simple/releases aarch64 就是 arm64 的包

如果你想自己编译可以参考 https://github.com/wangfenjin/simple/blob/master/.github/workflows/main.yml#L141

**Comment by wangfenjin** [comment]
上次回复得不对

**Comment by linxuda** [comment]
我在arm64架构的mac上使用的时候提示我是要引入dylib后缀的依赖文件，那个arch64的是os后缀的

**Comment by wangfenjin** [comment]
so是linux下面的；你有 mac的话直接下载编译就行了，不用什么配置

**Comment by wangfenjin** [comment]
readme里面有编译流程

**Comment by linxuda** [comment]
直接运行./build-ios.sh编译出来的是.a后缀的

**Comment by linxuda** [comment]
运行./build-and-run 命令打包出来的libsimple.dylib使用的时候也是报错mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')

**Comment by wangfenjin** [comment]
> 直接运行./build-ios.sh编译出来的是.a后缀的

iOS 的就是.a 的

**Comment by wangfenjin** [comment]
把完整日志贴出来我看下。你也可以自己搜索下，这种算是通用问题

**Comment by linxuda** [comment]
![image](https://github.com/wangfenjin/simple/assets/60088265/5b6e1b78-8e3e-4f18-b578-50614e579e16)
现在编译是这样的， 请问这是为啥

**Comment by wangfenjin** [comment]
看起来你用的库不支持这个方法？

**Comment by linxuda** [comment]
这种依赖是node全局依赖库么？还是系统的软件之类的？不太懂。。。

**Comment by wangfenjin** [comment]
https://stackoverflow.com/questions/58892028/sqlite3-connection-object-has-no-attribute-enable-load-extension

你这个错是 py 的

**Comment by wangfenjin** [comment]
你现在是想编译 iOS 的包，还是macOS 的包？

**Comment by wangfenjin** [comment]
macOS 我在 release 里面就有，iOS 的编译脚本也在仓库里你直接运行就行，iOS 的例子在 readme 里面也有

**Comment by wangfenjin** [comment]
> ![image](https://user-images.githubusercontent.com/60088265/267269152-5b6e1b78-8e3e-4f18-b578-50614e579e16.png)
> 现在编译是这样的， 请问这是为啥

如果你不用 python 连数据库，可以不管这个错

**Comment by linxuda** [comment]
> 译 iOS 的包，还是macOS 的包？

 macos的

**Comment by linxuda** [comment]
> 你现在是想编译 iOS 的包，还是macOS 的包？

okok，解决了，去下载了试了是可以用的，感谢🙏
