### ISSUE TITLE
增加flutter例子

### ISSUE THREAD

**Issue by lyyyann** [wangfenjin/simple#133]
你好，目前我通过flutter写手机APP，希望使用这个分词器，但不知道如何调用，否则在example中增加一个flutter的使用例子，非常感谢
------------
我在pub_dev上发现了fts5_simple 0.0.1 包，这个是您的吧？上面介绍支持PLATFORM[LINUX、MACOS、WINDOWS]，是不支持安卓和苹果手机吗？

**Comment by wangfenjin** [comment]
readme里面有java 的例子你可以参考，flutter 可能需要你自己做一个类似的，理论上跟连 SQLite差不多，只是需要加载插件

**Comment by wangfenjin** [comment]
pub_dev 不是我发布的，iOS和android都是支持的，不过可能需要你自己编译；readme里也有好几个小伙伴做的 iOS的例子

**Comment by SageMik** [comment]
我写了一个 Flutter Plugin，可以参考：[sqlite3_simple](https://github.com/SageMik/sqlite3_simple)

**Comment by wangfenjin** [comment]
> 我写了一个 Flutter Plugin，可以参考：[sqlite3_simple](https://github.com/SageMik/sqlite3_simple)

* 你用到的 libsimple.so 是你自己编译的吗？我看大部分人是问 android 怎么编译
* 你是把这个 plugin 发布了别人可以直接用对吗？

**Comment by SageMik** [comment]
> > 我写了一个 Flutter Plugin，可以参考：[sqlite3_simple](https://github.com/SageMik/sqlite3_simple)
> 
> * 你用到的 libsimple.so 是你自己编译的吗？我看大部分人是问 android 怎么编译
> * 你是把这个 plugin 发布了别人可以直接用对吗？

* 是的，libsimple.so 安卓端的编译可以参考 [simple-android-native](https://github.com/SageMik/simple-android-native) ，这个库也发布到了 Maven Central 上，纯安卓应用也可以引用，免去自己编译 libsimple.so 的步骤，但得自己加载 SQLite 和拓展；sqilte3_simple 在安卓端的实现也是依赖这个库；而 iOS 就是直接通过 Simple 的 `build-ios.sh` 编译的。
* 是的，这个 plugin 已经发布到 pub.dev 上了，Flutter 应用可以直接引用。
