### ISSUE TITLE
C# 可以调用这个吗

### ISSUE THREAD

**Issue by dudylan** [wangfenjin/simple#137]
我看下载的是dll 那C# 是否也可以使用这个工具。 如果用sqlite 库管理工具是否和sqlite 命令一致呢

**Comment by wangfenjin** [comment]
应该是没问题的

**Comment by dudylan** [comment]
很抱歉，我是一个C#初学者。 我尝试使用c# sqlite3 但sqlite3 的包没有load_extension 方法。 另一个问题是。我如果用C#调用的话是直接调用您dll里的方法。还是我要像C 那个样子

还是我要引用别的库

**Comment by wangfenjin** [comment]
https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/extensions

晚上一堆教程

**Comment by dudylan** [comment]
https://github.com/dudylan/SqliteCheck/  C# 调用dll example

**Comment by wangfenjin** [comment]
感谢！
