### ISSUE TITLE
在 macOS 13.6.1 上报 “libsimple.dylib” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by sethyuan** [wangfenjin/simple#138]
![image](https://github.com/wangfenjin/simple/assets/3410293/5660805d-5a4d-4851-adbb-75dd7d1f60b1)

麻烦帮忙看看是什么原因呢？加载扩展的时候报的。

**Comment by wangfenjin** [comment]
网上搜一下这个错误信息很多网站教你怎么做

**Comment by sethyuan** [comment]
在这个issue里或者README里加一个FAQ不是更好吗？相信后面还会有人遇到同样的问题。

**Comment by sethyuan** [comment]
另外如果要在Electron应用中使用的话部署到用户端时用户会不会也遇到这个问题？是不是应该开发者加下签名会更合适些？

**Comment by wangfenjin** [comment]
https://github.com/wangfenjin/simple/issues/100

想起来之前做过一个更新，但是好像不起作用

**Comment by wangfenjin** [comment]
苹果的开发者账户要钱的

**Comment by wangfenjin** [comment]
本地执行那个 xattr 命令是可以的

**Comment by sethyuan** [comment]
😂 理解，我先看看你给的链接，thanks！
