### ISSUE TITLE
大佬辛苦了，向你提一点检索的问题和建议

### ISSUE THREAD

**Issue by china-net-meng** [wangfenjin/simple#14]
-- 问题：
被检索字段内容很多时，查询性能明显下降。
同样的字段长度，对比fts4+icu分词器，simple分词明显要慢，具体没有测试慢多少。

-- 建议：
我认为是不是与使用拼音有关？
不论检索性能和拼音是否有关，我觉得simple应该提供一个可选参数，是否启用拼音检索
因为有些场景，比如字段内容是中英文混和的，使用拼音检索得到的结果有时候很离谱啊，把英文匹配上了。。

所以，我想请大佬加个flag，用于是否启用拼音检索。笔芯❤️

**Comment by yugaoxiang** [comment]
感谢两位大佬！
