### ISSUE TITLE
请问能不能为Android提供支持呢?

### ISSUE THREAD

**Issue by Grual1** [wangfenjin/simple#151]
windows上很好用,无奈本人是个C++小白,没有编译C++项目的经验, 希望作者能提供下安卓的so共享库

**Comment by wangfenjin** [comment]
不好意思我没有时间折腾 android

你可以参考 https://github.com/bowserf/android-cmake-sample/tree/master

**Comment by wangfenjin** [comment]
https://github.com/android/ndk-samples/tree/main/hello-libs

也可以看看这个

**Comment by Grual1** [comment]
> https://github.com/android/ndk-samples/tree/main/hello-libs
> 
> 也可以看看这个

谢谢你，感觉对没接触过C++的来说还是有点难以理解，我研究一下

**Comment by Grual1** [comment]
> 不好意思我没有时间折腾 android
> 
> 你可以参考 https://github.com/bowserf/android-cmake-sample/tree/master

我研究了一下您的代码,没有发现是怎么用拼音检索到中文的, 是因为在一开始插入数据到表中的时候,就已经将插入的中文建立好了拼音索引吗

**Comment by wangfenjin** [comment]
对，更多原理可以读这个 https://www.wangfenjin.com/posts/simple-tokenizer/  和 官方的 fts5 的文档

只是在 android 里面用需要解决的是上面编译的问题，c++ 代码可以不用看
