### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by mrpengxinwen** [wangfenjin/simple#155]
better-sqlite3 -v:9.6.0

const st1 = db.prepare(`SELECT simple_highlight(t_content_idx, 0, '<b>', '</b>') AS highlight_content FROM t_content_idx where         highlight_content match jieba_query('a')`)

console.log(st1.all())
t_content_idx表内容：
  {
    content: 'dadad dasdasd 王 张 李 的大赛大赛大赛的萨丰富的的繁荣同仁堂 ',
    file_name: '11.txt',
    ext: 'txt',
    hack: '0'
  }

2024-09-10 17:54:12 /home/runner/work/simple/simple/build/cppjieba/src/cppjieba/include/cppjieba/DictTrie.hpp:203 FATAL exp: [ifs.is_open()] false. open ./dict/jieba.dict.utf8 failed.

**Comment by wangfenjin** [comment]
看起来是找不到文件，可以用 jieba_dict() 这个函数设置下目录

https://github.com/wangfenjin/simple/blob/3fe428e2714d795438f1bc98961652e0c862ab1f/examples/node/better-sqlite3.js#L29

**Comment by mrpengxinwen** [comment]
> 看起来是找不到文件，可以用 jieba_dict() 这个函数设置下目录
> 
> https://github.com/wangfenjin/simple/blob/3fe428e2714d795438f1bc98961652e0c862ab1f/examples/node/better-sqlite3.js#L29

const dict_path = '/home/mkel-7/code/resources/'
db.prepare("select jieba_dict(?)").run(dict_path); 
还是不行
请问dict_path 是仅仅是个目录？

**Comment by wangfenjin** [comment]
真的很没有礼貌，问问题不说清楚，解决没解决也不知道就关掉

**Comment by mrpengxinwen** [comment]
解决了，对不起，大佬，学校网太卡了，加载不出来，不知道哪里就点到了关闭



---原始邮件---
发件人: "Wang ***@***.***&gt;
发送时间: 2024年9月11日(周三) 中午1:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [wangfenjin/simple] 崩溃 (Issue #155)




 
真的很没有礼貌，问问题不说清楚，解决没解决也不知道就关掉
