### ISSUE TITLE
在Windows下给 jieba_dict 一个带有中文的文件夹路径会崩溃

### ISSUE THREAD

**Issue by sethyuan** [wangfenjin/simple#160]
**Bug 描述**
如题

**重现步骤**
执行 `SELECT jieba_dict(?)` 时，如果路径中有中文就会报一个FATAL错误导致程序崩溃。

**环境信息**
 - 操作系统：Windows 10 64位
 - 有问题的软件版本：最新版

请问这个问题该如何避免呢？我没法控制用户给一个带有中文的文件夹。

**Comment by wangfenjin** [comment]
也许你可以把文件 copy 到一个你可以控制的目录里面

我没有 windows 电脑调试不了

**Comment by sethyuan** [comment]
我改写了代码，将dict文件夹拷贝到随程序控制的文件夹里并采用了相对路径来给jieba_dict传参（当然不包含中文字符），这样就避免这个问题了。
