### ISSUE TITLE
Snippet 获取的设置问题

### ISSUE THREAD

**Issue by yushaw** [wangfenjin/simple#163]
目前 snippet 获取时会找到所有匹配内容然后返回一个最佳的。
目前遇到一个问题是搜索一些常见字的时候会耗费很多的时间。

是否提供 fts5 中返回第一个 snippet 的逻辑？这样是不是就能快速的获取到内容，把时间压到数百毫秒的级别。

**Comment by wangfenjin** [comment]
这个函数逻辑挺复杂的话，如果加这个功能的话改动可能比较大

比较推荐的做法是你对匹配的结果做分页，比如匹配了十行数据就停止，针对十行数据做 snippet 应该还是很快的

**Comment by yushaw** [comment]
好的 感谢🙏
