### ISSUE TITLE
这个插件我想在spring boot项目中使用，有人如何结合mybatius使用呢

### ISSUE THREAD

**Issue by huangyuxuan0907** [wangfenjin/simple#164]
`@Bean
    public DataSource dataSource() {
        // 1. 首先配置 SQLite
        SQLiteConfig sqliteConfig = new SQLiteConfig();
        sqliteConfig.enableLoadExtension(true);

        // 2. 创建 HikariConfig 并设置所有属性
        HikariConfig hikariConfig = new HikariConfig();
        hikariConfig.setDriverClassName(driverName);
        hikariConfig.setJdbcUrl(url);
        hikariConfig.setMaximumPoolSize(1);
        hikariConfig.setConnectionTestQuery("SELECT 1");
        hikariConfig.setPoolName("springHikariCP");

        // 3. 设置所有数据源属性
        Properties props = sqliteConfig.toProperties();
        hikariConfig.setDataSourceProperties(props);

        // 4. 创建数据源
        dataSource = new HikariDataSource(hikariConfig);

        // 5. 初始化扩展
        try (Connection connection = dataSource.getConnection()) {
            String absolutePluginPath = getAbsolutePath("libsimple-osx-x64/simple.dll");
            String absoluteDictPath = getAbsolutePath("libsimple-osx-x64/dict");
            Statement statement = connection.createStatement();

            // 执行扩展加载 SQL
            String loadExtensionSql = "SELECT load_extension('" + absolutePluginPath + "', 'sqlite3_simple_init');";
            stmt.execute(loadExtensionSql);
            stmt.execute("SELECT jieba_dict('" + absoluteDictPath + "')");
            System.err.println("SQLite extensions loaded successfully.");
            
            String dropTableSql = "DROP TABLE IF EXISTS tbl;";
            statement.execute(dropTableSql);
            String tblCreateSql="CREATE VIRTUAL TABLE IF NOT EXISTS tbl USING fts5("
                    +"title,"
                    +"content,"
                    +"tokenize='simple'"
                    +");";
            statement.execute(tblCreateSql);
        } catch (Exception e) {
            throw new RuntimeException("Failed to load SQLite extensions: " + e.getMessage(), e);
        }
        return dataSource;
    }`
我使用以上的代码，初始化bean的时候没有报错。但是打开创建的表，却显示[SQLITE_ERROR] SQL error or missing database (no such tokenizer: simple)，也就是插件其实没有正确加载？

**Comment by wangfenjin** [comment]
没看到你 打开创建的表 的代码

你可以在 statement.execute(tblCreateSql); 下面尝试各种 insert 或者 select 看看是否正常

如果正常，我怀疑是你的 getConnection 函数有问题，我感觉dataSource.getConnection() 是不是一个连接池，然后只有你在处理化的时候获取到的这个连接有 simple

**Comment by huangyuxuan0907** [comment]
> 没看到你 打开创建的表 的代码
> 
> 你可以在 statement.execute(tblCreateSql); 下面尝试各种 insert 或者 select 看看是否正常
> 
> 如果正常，我怀疑是你的 getConnection 函数有问题，我感觉dataSource.getConnection() 是不是一个连接池，然后只有你在初始化的时候获取到的这个连接有 simple。
> 
> 解决方案就是给你的每个 connection 都保证加载了 simple

抱歉，其实是可以的。我是在IDEA中，右侧的Database中打开表，然后报错 [SQLITE_ERROR] SQL error or missing database (no such tokenizer: simple)，这里误导了我。Database应该是按照它自带的连接访问这个表，自然是访问不了，不清楚是否也可以配置。

**Comment by wangfenjin** [comment]
需要看你用的什么，有些是支持配置加载插件的

直观的还是通过命令行来访问
