### ISSUE TITLE
请教一个问题，能实现在某些表上启用拼音索引，同时在另外一些表上禁用拼音索引吗？

### ISSUE THREAD

**Issue by gcxfd** [wangfenjin/simple#18]
请教一个问题，能实现在某些表上启用拼音索引，同时在另外一些表上禁用拼音索引吗？

**Comment by wangfenjin** [comment]
可以啊，你看下 example.sql 里面，建表的时候不用 fts 表或者 tokenizer 选你想用的那个就行了

这个是可配的
