### ISSUE TITLE
关于特殊符字符报错

### ISSUE THREAD

**Issue by china-net-meng** [wangfenjin/simple#19]
您好，使用 @ & ,  等特殊符号检索时会报语法错误，sqlite3原始fts5 在match中使用特殊符号也会报错，并不是simple的原因，但是想问一下大神，在搜索时字符串包含@&这种特殊字符时，怎么处理呢？

**Comment by china-net-meng** [comment]
特殊符号两边加上双引号" 好像是屏蔽掉了，但我其实还是想检索这个字符的

**Comment by china-net-meng** [comment]
我发现中文的字符（比如。）就不会报错
而英文的字符（比如.）就报语法错误
能解决么大神

**Comment by wangfenjin** [comment]
我得看看有没有办法处理

你的 query 里面只有特殊字符还是会混杂其他字符一起？

**Comment by china-net-meng** [comment]
> 我得看看有没有办法处理
> 
> 你的 query 里面只有特殊字符还是会混杂其他字符一起？

只有特殊字符和混合特殊字符都会报错
这两种情况在实际用途中都是有可能存在的
比如：
```sql
select '    ', simple_highlight(t2, 0, '[', ']') from t2 where x match simple_query('@', '0');
select '    ', simple_highlight_pos(t2, 0) from t2 where x match simple_query('asdf@fdsa', '0');
```
这样就不会报错，但无法检索到@符号
```sql
select '    ', simple_highlight(t2, 0, '[', ']') from t2 where x match simple_query('"@"', '0');
```

**Comment by china-net-meng** [comment]
还有就是
中文字符就不会报错，比如
```sql
select '    ', simple_highlight(t2, 0, '[', ']') from t2 where x match simple_query('。', '0');
```
而英文字符就会报错，比如
```sql
select '    ', simple_highlight(t2, 0, '[', ']') from t2 where x match simple_query('.', '0');
```

**Comment by wangfenjin** [comment]
我做了一个 commit，可以支持大部分的字符，但是还有一个单引号的 case 解决不了

**Comment by wangfenjin** [comment]
目前的情况是对于单引号 simple_query 函数返回的字符串 match 不中，但是直接用 string 不用函数就能中

```sql
sqlite> select simple_query('''');
"''"
sqlite> select '    ', simple_highlight(t1, 0, '[', ']') from t1 where x match simple_query('''');
sqlite> select '    ', simple_highlight(t1, 0, '[', ']') from t1 where x match '"''"';
    |@English &special _characters."[']bacon-&and[']-eggs%
````

**Comment by wangfenjin** [comment]
我在 [stackoverflow](https://stackoverflow.com/questions/65899743/sqlite-custom-functions-as-match-string) 问了下，看有没有人会的

**Comment by wangfenjin** [comment]
@china-net-meng 看起来大家都不懂这个，没人回答我的问题

目前你有两个选择，如果不用搜索单引号用最新版本就行了；如果要支持单引号，你得自己拼搜索的 query，也就是不通过 simple_query 这个函数。这个函数做的事情就是帮你生成query，但是你自己要是知道规则的话自己也是可以生成的。

或者代码里面绕一下可能也可行，比如你先调用 select simple_query(your_input); 把string拿到，然后直接把这个 string 传给 match ，这样可能可行

**Comment by china-net-meng** [comment]
好的 谢谢大佬 我回头试一下 如果有合适方案再发上来

**Comment by wangfenjin** [comment]
@china-net-meng 我在 #27 添加了一个例子，说明也写在里面了。简单说有两种方案，一种是先通过 `select simple_query(input)` 把 query 拿到再去查，这样就能解决所有 case。

另一种就是针对有单引号的用这种方式，没有的情况用普通的方案查。

simple_query 只是一个普通的字符串函数，理论上这个函数在业务代码里实现也是可以的，我把它注册到 sqlite 里面是为了让使用方便

**Comment by china-net-meng** [comment]
谢谢大佬，根据你的提示，已经解决了，解决办法是，先simple_query然后拼接查询sql👍

**Comment by wangfenjin** [comment]
@china-net-meng 终于找到单引号的问题了，上面的 commit 已经做了修复。你不用再分两步做了，分两步反而单引号会有问题。
