### ISSUE TITLE
移动端使用问题

### ISSUE THREAD

**Issue by MachineMeAs** [wangfenjin/simple#2]
你好，怎么在移动端使用呢？

**Comment by wangfenjin** [comment]
你是想在 iOS 用还是 Android？

**Comment by MachineMeAs** [comment]
在iOS，我们使用的数据库是YapDatabase
| |
caimter
|
|
caimter@163.com
|
签名由网易邮箱大师定制


在2020年05月22日 17:02，Wang Fenjin<notifications@github.com> 写道：

你是想在 iOS 用还是 Android？

**Comment by MachineMeAs** [comment]
大哥，啥时候可以弄个swift版本的呀。我在项目中引入了C++一堆编译错误，调试了好些天了哦，可是小弟我对于C++是小白呐。希望可以得到你的帮助，谢谢哈！


| |
caimter
|
|
caimter@163.com
|
签名由网易邮箱大师定制


在2020年05月22日 17:07，caimter<caimter@163.com> 写道：
在iOS，我们使用的数据库是YapDatabase
| |
caimter
|
|
caimter@163.com
|
签名由网易邮箱大师定制


在2020年05月22日 17:02，Wang Fenjin<notifications@github.com> 写道：

你是想在 iOS 用还是 Android？

**Comment by wangfenjin** [comment]
我对 iOS 开发也不熟悉，得想想怎么搞；你们组里没人编译过 c++ 模块吗

**Comment by MachineMeAs** [comment]
我单独编译C++是可以通过，但是放进我们的项目中跟Swift混编就报错了，不知道怎么解决。


| |
caimter
|
|
caimter@163.com
|
签名由网易邮箱大师定制


在2020年06月1日 09:06，Wang Fenjin<notifications@github.com> 写道：

我对 iOS 开发也不熟悉，得想想怎么搞；你们组里没人编译过 c++ 模块吗

**Comment by wangfenjin** [comment]
是，苹果官方的文档也不清楚，我搜了一下都没有很好的文档。。

这个包基本没啥依赖，应该是好编译的

**Comment by MachineMeAs** [comment]
应该是C++标准的问题，我单独启一个项目编译是没有问题；但是放在我们项目中和Swift混编就报错


| |
caimter
|
|
caimter@163.com
|
签名由网易邮箱大师定制


在2020年06月1日 15:02，Wang Fenjin<notifications@github.com> 写道：

是，苹果官方的文档也不清楚，我搜了一下都没有很好的文档。。

这个包基本没啥依赖，应该是好编译的

**Comment by wangfenjin** [comment]
你是说 c++ 11 不行？如果是这个问题可以改，里面只有一两处用到了新的语法，其实不用也行

**Comment by wangfenjin** [comment]
如果是 11 不行你告诉我，我改一下相关代码

**Comment by MachineMeAs** [comment]
我先试一下吧，因为我也不太懂C++哈


| |
caimter
|
|
caimter@163.com
|
签名由网易邮箱大师定制


在2020年06月1日 15:08，Wang Fenjin<notifications@github.com> 写道：

你是说 c++ 11 不行？如果是这个问题可以改，里面只有一两处用到了新的语法，其实不用也行

**Comment by MachineMeAs** [comment]
好嘞，谢谢哈


| |
caimter
|
|
caimter@163.com
|
签名由网易邮箱大师定制


在2020年06月1日 15:09，Wang Fenjin<notifications@github.com> 写道：

如果是 11 不行你告诉我，我改一下相关代码

**Comment by wangfenjin** [comment]
如果有编译错误可以发出来我看看是不是 11 的问题

**Comment by zhijunkang** [comment]
大哥 可以给个联系方式 和你请教下如何在Android中集成使用

**Comment by wangfenjin** [comment]
> 大哥 可以给个联系方式 和你请教下如何在Android中集成使用

我对移动端不熟

**Comment by zrina1314** [comment]
> 大哥 可以给个联系方式 和你请教下如何在Android中集成使用

你弄出来了没，求同，不知道怎么生成so

**Comment by wangfenjin** [comment]
我把这个库的编译改成了 cmake，并且在 osx linux 和 windows 都可以编译了，你们可以看看

Android 和 iOS 在 github 上可以做 CI 吗？

**Comment by zrina1314** [comment]
我不知道是不是环境的问题还是其他的什么问题，我这边一直不成功，你那边能参考下这两个文章，把 ndk 编译不同的cpu 架构的脚本也集成到你这个脚本中么
https://segmentfault.com/a/1190000017900195
http://www.gaohaiyan.com/2253.html

**Comment by zrina1314** [comment]
使用最新代码编译貌似报错，报错信息如下：

zyf@zyfdeiMac ~ % /Users/zyf/Desktop/Project/simple-master/build-and-run ; exit;
 INFO  〈2021/01/09 11:00:34下午〉 Please enter your SUDO password: 
Password:

         « SUCCESS »    ✔  Your BashMatic has been successfully installed.


┌────────────────────────────────────────────────────────────────────────────┐
│  Simple Tokenizer                                                          │
└────────────────────────────────────────────────────────────────────────────┘


┌────────────────────────────────────────────────────────────────────────────┐
│  GCC                                                                       │
├────────────────────────────────────────────────────────────────────────────┤
│  Apple clang version 12.0.0 (clang-1200.0.32.21)                           │
│  Target: x86_64-apple-darwin19.6.0                                         │
│  Thread model: posix                                                       │
│  InstalledDir: /Library/Developer/CommandLineTools/usr/bin                 │
└────────────────────────────────────────────────────────────────────────────┘


┌────────────────────────────────────────────────────────────────────────────┐
│  GIT:    git version 2.29.0                                                │
└────────────────────────────────────────────────────────────────────────────┘


┌────────────────────────────────────────────────────────────────────────────┐
│  CMAKE:  cmake version 3.10.2  CMake suite maintained and supported by Kitware (kitware.com/cmake). 
└────────────────────────────────────────────────────────────────────────────┘


    Creating Build Folder...                                                

  ✔︎    ❯ mkdir -p build/run ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪〔      9 ms 〕    0 

    build...                                                                

  ✔︎    ❯ cd build/run ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪〔      7 ms 〕    0 
  ✘    ❯ cmake ../..  ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪〔     17 ms 〕    1 


    STDERR                                                                  

CMake Error: The source directory "/Users/zyf" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
\e[0m       # Command below will be shown with its output:
       ❯ make -j 12 
make: *** No targets specified and no makefile found.  Stop.

  ✘  ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪〔    111 ms 〕    2 
  ✘    ❯ make install | egrep -v 'gmock|gtest' ▪▪▪▪▪▪▪▪▪〔     35 ms 〕    1 


    STDERR                                                                  

make: *** No rule to make target `install'.  Stop.
  ✔︎         ❯ cd /Users/zyf ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪〔      7 ms 〕    0 
    testing...                                                              

       # Command below will be shown with its output:
       ❯ cd build/run 

  ✔︎  ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪〔      7 ms 〕    0 
       # Command below will be shown with its output:
       ❯ ctest . -V 
UpdateCTestConfiguration  from :/Users/zyf/build/run/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/zyf/build/run/DartConfiguration.tcl
Test project /Users/zyf/build/run
Constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
No tests were found!!!

  ✔︎  ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪〔    140 ms 〕    0 
       # Command below will be shown with its output:
       ❯ cd /Users/zyf 

  ✔︎  ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪〔      7 ms 〕    0 

┌────────────────────────────────────────────────────────────────────────────┐
│    « ERROR »   — You don't have the cmpiled sqlite3 binary yet.            │
└────────────────────────────────────────────────────────────────────────────┘


[进程已完成]

**Comment by wangfenjin** [comment]
你得 cd /Users/zyf/Desktop/Project/simple-master/ 到这个目录下， ./build-and-run

**Comment by wangfenjin** [comment]
@zhijunkang @zrina1314 

你们可以帮忙试下这个脚本吗？
https://github.com/google/oboe/blob/master/build_all_android.sh

理论上编译的流程是一样的。然后在代码里面模仿 https://www.javatips.net/api/org.sqlite.sqliteconfig 这个通过 `select load_extension` 来加载编译出来的文件

**Comment by wangfenjin** [comment]
已经有 iOS 的 demo 了

**Comment by JayRichrd** [comment]
> > 大哥 可以给个联系方式 和你请教下如何在Android中集成使用
> 
> 你弄出来了没，求同，不知道怎么生成so

请教大佬，是否有搞出Android使用的版本

**Comment by JayRichrd** [comment]
> 大哥 可以给个联系方式 和你请教下如何在Android中集成使用

请教大佬，是否有搞出Android使用的版本

**Comment by wangfenjin** [comment]
没有
