### ISSUE TITLE
已经编译成功并生成libsimple.dylib，但如何在项目中使用

### ISSUE THREAD

**Issue by lyyyann** [wangfenjin/simple#24]
我已经编译成功并生成libsimple.dylib，并将库引入到项目里，然后我在项目的入口主函数里直接使用sqlite3原生函数建表
int sqlite3_exec(
  sqlite3*,                                  /* An open database */
  **"CREATE VIRTUAL TABLE t1 USING fts5(x, tokenize = 'simple')”,**                           /* SQL to be evaluated */
  int (*callback)(void*,int,char**,char**),  /* Callback function */
  void *,                                    /* 1st argument to callback */
  char **errmsg                              /* Error msg written here */
);
然后报错如下："sqlite3_errmsg":"no such tokenizer: simple"

如何在项目中使用，还请指教。

**Comment by wangfenjin** [comment]
sqlite3*, /* An open database / 你拿到这个链接之后，需要 load_extension，不同语言可能方法名不同，但是应该都有对应的方法

参考这里 https://stackoverflow.com/a/8322827/1203241

你如果成功了把你的代码也分享到这吧，让别人也知道

**Comment by wangfenjin** [comment]
我加了一个 [cpp](https://github.com/wangfenjin/simple/blob/master/examples/cpp/main.cc) 的例子，你可以看看

其他语言应该跟这个类似

**Comment by lyyyann** [comment]
感谢大佬专业、及时的解答，使用的时候加上如下两句就可以正常用了
// load simple
  rc = sqlite3_enable_load_extension(db, 1);
  handle_rc(db, rc);
  rc = sqlite3_load_extension(db, "libsimple", NULL, NULL);
