### ISSUE TITLE
创建索引表问题

### ISSUE THREAD

**Issue by lyyyann** [wangfenjin/simple#26]
> 3. 可扩展性高
       高可扩展性要求搜索表结构和业务解耦。SQLite FTS官网上的例子，都是以单索引表的方式，每一列对应业务的某一个属性，当对应业务发生变化，需要修改索引表的结构。为了解决业务变化而带来的表结构修改问题，微信把业务属性数字化，设计如下的表结构：
[http://www.52im.net/data/attachment/forum/201710/18/125902yj4jujjjonen5obo.jpeg](url)
       IndexTable负责全文搜索的索引建立，它和逻辑无关，当搜索关键词时，只需要找到对应的DocId即可。MetaTable负责业务逻辑的过滤，通过Type和SubType来过滤对应业务的数据，最后输出BusItemId。

如上是《微信全文搜索优化之路》一文中针对索引表的介绍，我对索引有几个问题想请教一下：
1.业务表是正常的程序的数据表，还要再为了全文搜索再多建立一份索引表，是吗？我直接将我的业务数据表在创建的时候按虚表建立行吗？（例如create virtual table tablename using fts5(列名1,列名2,tokenize = 'simple')）
2.如果再多建立一份索引表，那是不是每一个业务表和对应的索引表的表字段是完全相同？
3.如果再多建立一份索引表，那数据库的大小是不是加倍了，尤其是把文件或图片影片存入数据库的情况（BLOB类型）？
4.原文中【为了解决业务变化而带来的表结构修改问题，微信把业务属性数字化】，这也是我想要的，能否帮助贴下原文中提到的【索引表-IndexTable】和【数据表-MetaTable】的建表语句？

非常非常感谢！！！

**Comment by wangfenjin** [comment]
你思考的都是对的，关于你的问题：

1. 你可以考虑建两个表，一个正常的一个 fts 表；也可以只建一个 fts 表；但是 fts 表有个限制是它的索引不同于普通索引，所以如果你出了需要查文字的字段，还有其他比如 == 的查询，那可能就比较慢了
2. 对于第2和第3个问题，结合第1个问题，都是一样的解法，就是你建一个普通的表，所有数据都存里面；再建一个 fts 表，但是这个 fts 表是只存索引不存真正数据的，叫做 External Content Tables。通过这个 table 就能解决数据重复的问题，也能解决其他字段的查询效率问题。
3. 第4个问题建表语句你看文中的图就很容易写出来了，自己去想。另外微信这个思路其实用的不是  External Content Tables，而是把需要 fts 的字段抽出来然后走外键关联。也许是因为微信的业务太复杂了才这么做，我个人觉得一般情况下 External Content Tables 更方便。

关于 External Content Tables 你可以看看这个文章，写得还是非常清楚的 https://kimsereylam.com/sqlite/2020/03/06/full-text-search-with-sqlite.html

回头有时间我也可以写一个类似的中文版把你这个问题系统回答下

**Comment by lyyyann** [comment]
大神的解答和这篇文章【 https://kimsereylam.com/sqlite/2020/03/06/full-text-search-with-sqlite.html】完美的解答了我对于虚拟表、索引等的疑惑。
非常感谢！
