### ISSUE TITLE
希望能在windows上使用，并且来一个比较详细的编译方法

### ISSUE THREAD

**Issue by lonllua** [wangfenjin/simple#3]
最近基于electron开发windows桌面应用，由于各种原因使用了sqlite数据库，想使用fts5并支持中文分词，大佬的项目很不错！star了

**Comment by wangfenjin** [comment]
refer to #5

**Comment by wangfenjin** [comment]
参见项目 appveyor.yml 文件

**Comment by wangfenjin** [comment]
参见项目 appveyor.yml 文件

**Comment by dzcpy** [comment]
项目的 appveyor.yml 文件在哪里能找到？

**Comment by wangfenjin** [comment]
> 请问项目的 appveyor.yml 文件在哪里能找到？

换成 gitlab ci 了 https://github.com/wangfenjin/simple/blob/master/.github/workflows/main.yml#L13-L63

https://github.com/wangfenjin/simple/runs/2480900796?check_suite_focus=true
