### ISSUE TITLE
关于simple_highlight函数的返回值问题

### ISSUE THREAD

**Issue by lyyyann** [wangfenjin/simple#36]
我创建虚拟表如下：
CREATE VIRTUAL TABLE t1 USING fts5(x,y, tokenize = "simple");
插入记录如下：
insert into t1 values ("周杰伦 Jay Chou:最美的不是下雨天，是曾与你躲过雨的屋檐","我是y列")
然后进行查询如下：
select simple_highlight(t1, 0, '[', ']') from t1 where t1 match simple_query('y列');
返回的是"周杰伦 Jay Chou:最美的不是下雨天，是曾与你躲过雨的屋檐"，这是为什么呢，而我想到的是返回“我是[y列]”，还请大神帮助看看

**Comment by wangfenjin** [comment]
```sql
select simple_highlight(t1, 1, '[', ']') from t1 where t1 match simple_query('y列');
```
highlight 的第二个参数表示你想 select 的那一列的下标，下标从 0 开始；你这个例子如果想展示 y 列第二个参数就是 1

https://www.sqlite.org/fts5.html#the_highlight_function

另外如果你只想 match y 列可以这么写：
```sql
select simple_highlight(t1, 1, '[', ']') from t1 where y match simple_query('y列');
```

**Comment by lyyyann** [comment]
> ```sql
> select simple_highlight(t1, 1, '[', ']') from t1 where t1 match simple_query('y列');
> ```
> 
> highlight 的第二个参数表示你想 select 的那一列的下标，下标从 0 开始；你这个例子如果想展示 y 列第二个参数就是 1
> 
> https://www.sqlite.org/fts5.html#the_highlight_function
> 
> 另外如果你只想 match y 列可以这么写：
> 
> ```sql
> select simple_highlight(t1, 1, '[', ']') from t1 where y match simple_query('y列');
> ```

我希望的效果是，还是用 t1 match simple_query('y列');，对于命中的结果，可以返回对应的列，只不是指定哪一定来显示，这有办法吗？

**Comment by wangfenjin** [comment]
做不到；这个和普通的 sql 原理是一样的， select 后面跟着哪些列是需要用户自己指定的，你也可以同时返回多个列：
```sql
select simple_highlight(t1, 0, '[', ']') , simple_highlight(t1, 1, '[', ']') from t1 where y match simple_query('y列');
```
但是不管怎么着都需要你自己指定。

有两种方法可以绕过这个问题，一个是通过 simple_highlight_pos 函数，这个函数会返回 match 的位置，判断返回是否为空，就知道这一列有没有 match 了
```sql
select simple_highlight_pos(t1, 0) , simple_highlight(t1, 1) from t1 where y match simple_query('y列');
```
另一种方法是类似[这篇文章](https://cloud.tencent.com/developer/article/1194171)提到的，把需要索引的数据打平，然后再通过关联属性去查询是哪个字段命中了。

![liuyqxkim0](https://user-images.githubusercontent.com/4160646/108612537-9c9b4c00-7424-11eb-8dde-69bfa2dd5a51.jpeg)

无论如果，sql select 只返回你指定的列这一点是改不了的

**Comment by lyyyann** [comment]
明白了，非常感谢！！！
