### ISSUE TITLE
关于jieba分词的一点问题

### ISSUE THREAD

**Issue by china-net-meng** [wangfenjin/simple#37]
您好，使用最新版带jieba分词功能的simple，有如下2点问题：
1. 能否把dict目录再次融合进libsimple库中，只要一个动态库文件？
2. jieba分词首次查询非常慢，第二次之后速度正常，是不是第一次加载dict目录下文件导致速度慢？能否优化一下呢

**Comment by wangfenjin** [comment]
1 理论上是可以做的，我需要再看一下；结巴分词的文件更多，也比较大，你确定想要直接编译进去吗？

2 对，目前是首次查询的时候才加载分词文件，所以需要消耗一定时间；这个时间是没法消失的，如果不想在首次查询的时候慢，那就在首次 load 整个扩展的时候慢，因为不是所有人都可能用到 jieba 的功能，所以就选择在用的时候才加载。这是常规的做法

**Comment by china-net-meng** [comment]
> 1 理论上是可以做的，我需要再看一下；结巴分词的文件更多，也比较大，你确定想要直接编译进去吗？
> 
> 2 对，目前是首次查询的时候才加载分词文件，所以需要消耗一定时间；这个时间是没法消失的，如果不想在首次查询的时候慢，那就在首次 load 整个扩展的时候慢，因为不是所有人都可能用到 jieba 的功能，所以就选择在用的时候才加载。这是常规的做法

您好：
1. 不打包进去也行，我看引用dict目录中的文件使用的是相对目录，您帮忙改成同级的绝对目录或者麻烦告诉我怎么改成同级的绝对目录？我这边的问题是引用dict目录不能使用相对目录，相对目录会报错。。因为我这里是在electron中使用
2. 这个问题我可以通过一个闲置的时间节点预先执行一下jieba_query解决，主要是第一个问题，比心

**Comment by wangfenjin** [comment]
同级你说的是哪一级？你是说不要 ./dict/xxx.file 而改成 ./xxx.file 吗？目前应该是你的程序运行的目录的相对目录。

如果你想改成 ./xxx.file 这样，可以 https://github.com/wangfenjin/simple/blob/master/src/simple_tokenizer.cc#L73 改这里的试试

**Comment by wangfenjin** [comment]
理论上你把 libsimple.so 放在哪，把 ./dict/ 也放在它的同级就能读到

**Comment by wangfenjin** [comment]
哦我懂了，是因为你的libsimple.so 加载的时候也是一个相对目录是吗？所以你想变成./path/to/lib/dict/xxx ?

**Comment by china-net-meng** [comment]
> 哦我懂了，是因为你的libsimple.so 加载的时候也是一个相对目录是吗？所以你想变成./path/to/lib/dict/xxx ?

我加载libsimple.so是绝对目录，使用时dict目录不能放在libsimple同级，而是需要放在项目根目录才行。。。

**Comment by wangfenjin** [comment]
嗯我知道怎么解了，我加一个参数让你传入 dict 的路径吧！

**Comment by china-net-meng** [comment]
> 嗯我知道怎么解了，我加一个参数让你传入 dict 的路径吧！

dict路径预计要在那步传呢？因为我这边dict路径是变化的，打包后软件包所在位置是不同。

**Comment by china-net-meng** [comment]
> 嗯我知道怎么解了，我加一个参数让你传入 dict 的路径吧！

如果是编译lib时传路径，还是无法解决运行时目录的问题。。。

**Comment by wangfenjin** [comment]
CREATE VIRTUAL TABLE t2 USING fts5(x, tokenize = 'simple 0');

建表的时候传，第一个参数控制拼音，第二个参数文件路径，不传就是默认的

**Comment by china-net-meng** [comment]
> CREATE VIRTUAL TABLE t2 USING fts5(x, tokenize = 'simple 0');
> 
> 建表的时候传，第一个参数控制拼音，第二个参数文件路径，不传就是默认的

感觉建表时传入dict路径好像不够灵活啊。。。

**Comment by china-net-meng** [comment]
大神，您这边把 ./dict 改成 filepath( libsimple.so文件所在位置绝对路径 ) + dict 这种形式的，应该就能解决我这种问题了吧？

**Comment by china-net-meng** [comment]
就是不知道在动态库中执行获取当前文件位置，filepath( libsimple.so文件所在位置绝对路径 )获取的是sqlite3的绝对路径还是动态库的。。。

**Comment by wangfenjin** [comment]
灵活还是灵活的，甚至不同的表都可以传不同的 dict 目录，就是有点麻烦

我试试吧看动态库能不能获取到自己当前的文件路径

**Comment by wangfenjin** [comment]
获取自己的路径挺麻烦的，主要是不同平台的方式都不一样，很难做到面面俱到

感觉让用户传进起来是最好的方案


https://sqlite.org/forum/forumpost/7ffc71acf0 在这里问了一下，看有人理我没有

**Comment by wangfenjin** [comment]
@china-net-meng 

`select jieba_dict('/path/to/dict/')` load 拓展之后，用这个来设置 dict 的路径，你试试吧，有问题再反馈

**Comment by china-net-meng** [comment]
灰常好用啊 大佬🌹
