### ISSUE TITLE
如何实现顺序匹配

### ISSUE THREAD

**Issue by crazyeruca** [wangfenjin/simple#40]
大佬辛苦！

比如原文“上午”，检索“午上”也能匹配上，请问有啥方法能做到保证顺序？因为匹配的索引本身是连续的，没法通过索引是否有间隔判断是否连续。

**Comment by crazyeruca** [comment]
发现在simple_highlight里根据词的顺序可以做到
`  int iInst = 0;
  int nInst;
  int iop = -1;
  rc = pApi->xInstCount(pFts, &nInst);
  while (rc == SQLITE_OK && iInst < nInst) {
      int ip;
      int ic;
      int io;
      rc = pApi->xInst(pFts, iInst, &ip, &ic, &io);
      if (rc == SQLITE_OK) {
          if (ic == iCol) {
              if (iop > ip) {
                  sqlite3_result_null(pCtx);
                  return;
              }
              iop = ip;
          }
          iInst++;
      }
  }`

**Comment by wangfenjin** [comment]
simple_highlight 是拿来高亮输出的。想实现连续匹配可以用 jieba_query:

select '    ', simple_highlight(t1, 0, '[', ']') from t1 where x match jieba_query('上午');

**Comment by wangfenjin** [comment]
关于 jieba_query 的用法可以看 readme 里面的链接

**Comment by crazyeruca** [comment]
> simple_highlight 是拿来高亮输出的。想实现连续匹配可以用 jieba_query:
> 
> select ' ', simple_highlight(t1, 0, '[', ']') from t1 where x match jieba_query('上午');

jieba_query对中文输入是可以实现连续匹配，但是如果输入的是拼音，还是会有顺序问题，比如输入wushang，也会匹配原词“上午”

**Comment by wangfenjin** [comment]
@crazyeruca 把拼音改成连续匹配了
