### ISSUE TITLE
build 時，出現大量錯誤，須改 pinyin.h

### ISSUE THREAD

**Issue by gdrmk** [wangfenjin/simple#42]
计算机环境：   visual studio 2019,  windows 10, 
但系统是繁体中文。

在build 时，出现 100多个错误，不是警告。

解决方法1：将 pinyin.h 檔之 tone_to_plain 中的怪字母，全改成一般英文字母，即可。当然其拼音的功能也就没了。

或者用 
解决方法2：将 pinyin.h 重新存成 utf8 但有 bom ，(原档是utf8无bom)。

**Comment by wangfenjin** [comment]
你可以把带 bom 的文件提交一个 PR 看看 CI 能过不，CI 能过的话可以 merge

**Comment by wangfenjin** [comment]
@gdrmk 可以帮忙看看吗？我没有 windows 机器没法做测试

**Comment by crazyeruca** [comment]
用u8装饰一下带音标的字符应该也可以

**Comment by wangfenjin** [comment]
没人回复我关了
