### ISSUE TITLE
启动时间优化！

### ISSUE THREAD

**Issue by InnotSagg** [wangfenjin/simple#44]
项目非常好用，但是是否可以优化下启动时间！

尝试在安卓开发里使用simple，高通855CPU，载入sqlite3_simple_init后sqlite3_open(":memory:", &db);需要4.928秒执行时间，无法实际使用。

在X86 intel 4.6G CPU， 启动需要2.566s。 

希望可以给点提示，是否有办法优化启动时间。

**Comment by wangfenjin** [comment]
https://github.com/wangfenjin/simple/blob/master/examples/cpp/main.cc#L53-L61

理论上是先 open，再 load simple 扩展，load 这一下应该不会耗时太多，你能让我看看你的代码变更吗，感觉不是 load 拓展引起的


目前确认比较慢的是第一次调用 jieba_query 会比较慢，这个是因为需要载入分词规则引起的，解决方案是另起一个线程预热一下，参考 #37 

其他函数不应该有特别慢的情况

**Comment by wangfenjin** [comment]
我改了一下，把拼音数据的初始化滞后了，所以 load 扩展的时候会很快

第一次使用拼音分词的时候会变慢因为还是需要初始化拼音数据。可以参考 #37 的思路，load 扩展之后通过异步 `select simple_query('pinyin')` 这样预热一下，这样后续插入和查询操作也会很快

你试一下如果还有问题可以再打开这个 issue

**Comment by wangfenjin** [comment]
@InnotSagg 另外你可否分享一下你是怎么在 Android 里面用的？帮忙解决下 #2 中大家提到的问题

**Comment by crazyeruca** [comment]
我用creal将拼音map数据序列化到本地文件中，每次初始化用creal加载文件，实测1毫秒加载完成。

**Comment by wangfenjin** [comment]
@crazyeruca 你是说你在别的项目中用了 cereal 这个库吗？

我现在其实是把拼音文件编译成一个 .h 文件包含到程序里面了的，现在慢我感觉是因为我初始化的时候用了一点正则，可以考虑把这个改掉。

真正读文件的话 1ms 不至于吧，毕竟要去读磁盘

**Comment by crazyeruca** [comment]
> @crazyeruca 你是说你在别的项目中用了 cereal 这个库吗？
> 
> 我现在其实是把拼音文件编译成一个 .h 文件包含到程序里面了的，现在慢我感觉是因为我初始化的时候用了一点正则，可以考虑把这个改掉。
> 
> 真正读文件的话 1ms 不至于吧，毕竟要去读磁盘

现在编译到.h文件中加载拼音应该不会有性能问题吧，我当时也尝试把拼音文件转换成.h文件（直接转换到map），当时数据结构太长，编译器编译不过去，后来我用cereal 序列化了拼音的map数据，初始化每次都加载这个数据文件，实测加载1ms

**Comment by wangfenjin** [comment]
@crazyeruca 现在是编译成 .h 文件了的，用的这个东西 https://github.com/wangfenjin/simple/blob/master/CMakeLists.txt#L25-L28

性能得测试下，要么是这样编译还是慢，要么是正则慢

**Comment by wangfenjin** [comment]
@InnotSagg 把启动时间优化到了 500ms

如果想彻底优化还是需要把 pinyin.txt 处理一下
