### ISSUE TITLE
如何在 electron 端使用呢

### ISSUE THREAD

**Issue by everlose** [wangfenjin/simple#48]
愁，接到了一个需求要在一个 electron 应用里搞全文搜索。
打算用 sqlite fts extension，但他对中文支持很差，想找个 tokenizer，但我不知道该怎么把你的这个 tokenizer 编译成 electron 能用的 sqlite 。
能提供点思路吗？

**Comment by wangfenjin** [comment]
你用的是 js 访问 sqlite 吧？这个 js 的库应该也有办法加载编译好的扩展

所以你需要做的是根据你的系统编译好扩展，然后用 js 加载进去

加载的例子参考 https://github.com/wangfenjin/simple/blob/master/examples/cpp/main.cc

**Comment by everlose** [comment]
大佬，看起来我使用了 node-sqlite3 然后用他的 load 能力，看起来能正常加载你编译后的 output/bin/libsimple.dylib 这个扩展文件了。只是使用起来仍旧不对劲，查不出来东西

```
/**
 * Shows how to use chaining rather than the `serialize` method.
 */
"use strict";

var sqlite3 = require('sqlite3').verbose();
var db;

function createDb() {
  console.log("createDb chain");
  db = new sqlite3.Database('chain.sqlite3', function() {
    db.loadExtension('./output/bin/libsimple.dylib');
    createTable()
  });
  
}


function createTable() {
  console.log("createTable t1");
  // db.run("CREATE TABLE IF NOT EXISTS lorem (info TEXT)", insertRows);
  db.run(`CREATE VIRTUAL TABLE t1 USING fts5(x, tokenize = "simple")`, insertRows);
}

function insertRows() {
  console.log("insertRows Ipsum i");
  var stmt = db.prepare("INSERT INTO t1 VALUES (?)");

  stmt.run("周杰伦 Jay Chou:最美的不是下雨天，是曾与你躲过雨的屋檐 ");
  stmt.run("昼短苦夜长 何不秉烛游");
  stmt.run("假如我是一只鸟, 我也就应用嘶哑的喉咙歌唱");
  stmt.run("这被暴风雨所打击的土地, 这永远汹涌着我们的悲愤的河流,");

  stmt.finalize(readAllRows);
}

function readAllRows() {
  db.run(`select simple_highlight(t1, 0, '[', ']') from t1 where x match simple_query('Jay');`, function (err, rows) {
    console.log('query result: ', err, rows);
    closeDb();
  })
}

function closeDb() {
  console.log("closeDb");
  db.close();
}

function runChainExample() {
  createDb()
}

runChainExample();
```

跑起来的结果是 

```
% node main.js
createDb chain
createTable t1
insertRows Ipsum i
query result:  null undefined
closeDb
```

query result: null undefined，找不到东西。。它应该是加载成功了你编译后的东西吧，因为我运行 `select simple_highlight()` 时并没有报错。。。困惑了

**Comment by wangfenjin** [comment]
db.run(`CREATE VIRTUAL TABLE t1 USING fts5(x, tokenize = "simple")`, insertRows);

simple 用单引号，不知道有影响没有。 'simple'

**Comment by everlose** [comment]
db.run("select * from t1; ")  的结果的确是 null
select simple_query('Jay');   还是 null
select fts5(?1);  结果还是 null

这里的单引号和双引号是没有区别的。。

本地的确生成了 db， 我用了 ui 工具查看，看起来里面明明有数据的样子

![image](https://user-images.githubusercontent.com/8710568/118949451-d4665100-b98b-11eb-9017-332c921d6b7e.png)

**Comment by everlose** [comment]
![image](https://user-images.githubusercontent.com/8710568/118949871-3c1c9c00-b98c-11eb-8d14-ffcccd7a83a3.png)
难道这个db其实还是没有正确的把 tokenizer 加载进来的吗。。

**Comment by everlose** [comment]
哎，应该在代码里的确load成功了你的 dylib 的，去掉引用 load 的那段代码，运行起来就会直接抛错
```
Error: SQLITE_ERROR: no such function: simple_highlight
```

**Comment by everlose** [comment]
我知道了，是我不会用 node-sqlite3

换成 

```
db.each(`select simple_highlight(t1, 0, '[', ']') from t1 where x match simple_query('Jay');`, function (err, msgs) {
    console.log(`search res: `, err, msgs)
    closeDb();
  });
```

我就能够得到结果

```
'周杰伦 [Jay] Chou:最美的不是下雨天，是曾与你躲过雨的屋檐 '
```

不好意思用这么傻逼的问题打扰了你这么久。。

**Comment by wangfenjin** [comment]
好那我关掉 issue 了，有问题可以再提
