### ISSUE TITLE
匹配“中华人民共和国国歌”的国表现有点微妙

### ISSUE THREAD

**Issue by everlose** [wangfenjin/simple#49]
我有些想不太懂

```
drop table if exists t1
CREATE VIRTUAL TABLE t1 USING fts5(_id, text, tokenize = 'simple')
INSERT INTO t1 VALUES ("JJSUUAKAQQEWE", "中华人民共和国国歌")
select _id, simple_highlight(t1, 1, '[', ']') as text from t1 where text match simple_query('中华国歌');

# 查询结果： [ { _id: 'JJSUUAKAQQEWE', text: '[中华]人民共和[国国歌]' } ]

select _id, simple_highlight(t1, 1, '[', ']') as text from t1 where text match simple_query('中华人民共和国');
# 查询结果： [ { _id: 'JJSUUAKAQQEWE', text: '[中华人民共和国国]歌' } ]
```

为什么会匹配 “国国” 呢？

**Comment by wangfenjin** [comment]
因为 simple_query 是单字匹配，也就是把 query 中的字挨个拆开匹配。

如果你想按照词组匹配可以用 jieba_query:
```
sqlite> select _id, simple_highlight(t1, 1, '[', ']') as text from t1 where text match jieba_query('中华国歌');
JJSUUAKAQQEWE|[中华]人民共和国[国歌]
sqlite> select _id, simple_highlight(t1, 1, '[', ']') as text from t1 where text match jieba_query('中华人民共和国');
JJSUUAKAQQEWE|[中华人民共和国]国歌
```

**Comment by wangfenjin** [comment]
匹配的原理 README.md 里有文章链接介绍

**Comment by everlose** [comment]
我在使用 jieba_query 的时候遇到了点麻烦

```
2021-05-24 10:28:02 /Users/chenziyun/workspace/github/simple/build/run/cppjieba/src/cppjieba/include/cppjieba/DictTrie.hpp:203 FATAL exp: [ifs.is_open()] false. open ./dict/jieba.dict.utf8 failed.
zsh: abort      node main.js
chenziyun@everloseMacBoock desk-example % 
```

我在 simple 文件夹下编译成 output，然后把这个output复制到 desk-example 目录下，desk-example 里编译sqlite并引入 desk-example/output 里的 dylib。

**Comment by wangfenjin** [comment]
你可以在代码里面打印一下当前目录是啥，默认会去当前目录下找 ./dict/jieba.dict.utf8 这个文件；如果这个文件不在这个相对路径上，你可以通过 jieba_dict() 这个函数设置文件的绝对路径

**Comment by everlose** [comment]
被 node 包了一层后我也不清楚是怎么能调用到 jieba_dict 方法了。。总之我在项目里把 dict 提到项目的根路径下，是能使用的 jieba_query 的。
以前我使用过 nodejieba，它分词的结果会是 "中华人民共和国" “国歌” “中华” “华人” “人民” “共和国”，所以单独搜 jieba_query 的 "国" 字就不会得到结果，头大。

**Comment by everlose** [comment]
我觉得很纳闷
若按单字索引，比如说 “中华人民共和国国歌” 就一定能匹配 “民共” 和 “人和”
但其实微信和飞书上实验， “中华人民共和国国歌”  能匹配 “民共” 但是不会匹配 “人和”。

若按 jieba 分词匹配，“民共” 应该也不是能被推断为一个词汇的，就匹配不中。

他们的分词规则，可能和我们想的还是不一样

**Comment by wangfenjin** [comment]
"若按 jieba 分词匹配，“民共” 应该也不是能被推断为一个词汇的，就匹配不中。" 为什么？你试过 jieba 的分词结果吗？

 “但其实微信和飞书上实验， “中华人民共和国国歌” 能匹配 “民共” 但是不会匹配 “人和”。” 微信最早是单子匹配，不知道从哪个版本开始改了，加了一些逻辑，但是没有文章描述他们的规则。飞书就更不透明了。

“ 以前我使用过 nodejieba，它分词的结果会是 "中华人民共和国" “国歌” “中华” “华人” “人民” “共和国”，所以单独搜 jieba_query 的 "国" 字就不会得到结果，头大。” 是有什么问题吗？给个具体的 sql 例子

“被 node 包了一层后我也不清楚是怎么能调用到 jieba_dict 方法了。。总之我在项目里把 dict 提到项目的根路径下，是能使用的 jieba_query 的。” jieba_dict 跟 jieba_query 一样是注册的一个 sql 函数，能调到 jieba_query 就能调用 jieba_dict

**Comment by wangfenjin** [comment]
你不用去猜微信具体的规则是啥，很难罗列出来他们所有的规则；如果你觉得有不对的 case 可以列出来具体的 case 看，是jieba分词的问题还是什么别的问题

**Comment by everlose** [comment]
> 你不用去猜微信具体的规则是啥，很难罗列出来他们所有的规则；如果你觉得有不对的 case 可以列出来具体的 case 看，是jieba分词的问题还是什么别的问题

是的，我找到的资料也在说微信用的单字分词。。只是现在被测到 上述的话里要匹配 “民共”，但不匹配“人和”，大佬你有什么想法吗？

**Comment by wangfenjin** [comment]
http://cppjieba-webdemo.herokuapp.com/

你用 结巴 分词的 demo 测试一下就知道，民共 分词还是 民共，所以能命中；人和 分词是 人 和 分开的，所以还是能命中

如果要让 人和 不命中，那就要去给 结巴 分词加一个规则告诉它；目前人和不在 结巴 分词词典里

$ rg 人和
jieba.dict.utf8
25569:人和事 3 n
25570:人和镇 2 n
90488:地利人和 4 nz
100242:天时地利人和 11 nz
161153:政清人和 3 n
161195:政通人和 9 n

idf.utf8
61715:天时地利人和 12.1089181827
132796:政通人和 13.2075304714
232168:人和事 10.4994802703
255697:人和镇 13.900677652
258005:地利人和 13.2075304714

**Comment by wangfenjin** [comment]
另外 user.dict.utf8 这个文件是可以自己修改的，比如你把 `人和 10000 nz` 加到最后一行，分词就会把 人和 分到一起，就不会命中 中华人民共和国国歌 了

**Comment by everlose** [comment]
还是感谢大佬指点，但我觉得应该不是通过把“人和”设为一个分词来解决不命中的问题。
之前我只是随便举了个例子，其实微信里的一句话，这样不相邻的两个字表现起来就是搜不到，而相邻的两个字虽然不是一个词语但是却能搜得到。

**Comment by wangfenjin** [comment]
这就是搜索的规则啊，要么改索引要么改query，不然那你要怎么解决呢？

另外你需要考虑考虑实际的场景和例子，搜索本来就是有了一个通用版本之后，不断通过整理bad case不断优化的过程

**Comment by everlose** [comment]
嗯，是呀，好为难。所以我们还是暂时用 jieba_query 吧。

**Comment by yugaoxiang** [comment]
大佬能给一下联系方式吗？最近开始接入了，可能问题有点多。我搜索的时候jieba_query或者simple_query或者只match，都能用拼音搜出来，可以关闭吗？有的表需要拼音汉子都能搜索的时候再打开

**Comment by wangfenjin** [comment]
GitHub 的用户名就是我的微信；有问题也可以直接提issue 问
