### ISSUE TITLE
插入数据时出现 sqlite3.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by am009** [wangfenjin/simple#56]
问题：
我在使用simple分词器时，插入数据的时候会出现sqlite3.DatabaseError: database disk image is malformed报错，切换成其他分词器就不会出现。(数据库使用了external_content_tables。)
比较奇怪的一点是，插入报错后commit数据库，然后再重新打开，好像数据库也没有损坏。
感觉这个问题也许比较难debug？不过感觉挺影响使用体验的

环境：
windows 10 使用python的load_extension加载simple.dll 
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
https://github.com/wangfenjin/simple/releases/tag/v0.0.2

附件是我提取出来的较小的复现数据和建库插入的python脚本，在上一层目录放置解压好的win32的release里下载的simple分词器的dll即可运行。希望能在其他环境下稳定复现。

[malformed.zip](https://github.com/wangfenjin/simple/files/6958735/malformed.zip)

**Comment by wangfenjin** [comment]
@nmgwddj 我试了一下，加上你上次 MR 提到的 std::iscntrl 的判断就不会报错了，有时间提个 MR 吗？谢谢

**Comment by wangfenjin** [comment]
@am009 谢谢反馈，我们等一下 @nmgwddj 的回应，如果他没时间稍后我会提交一个修复

**Comment by nmgwddj** [comment]
> @am009 谢谢反馈，我们等一下 @nmgwddj 的回应，如果他没时间稍后我会提交一个修复

Sorry，最近有点忙，我今晚整理一下 PR 发上来，我们有复用您的项目代码，改动比较多，我需要单独抽离出来整理一下。

**Comment by wangfenjin** [comment]
@nmgwddj 好的，辛苦了

**Comment by am009** [comment]
太强了，膜拜大佬们

**Comment by wangfenjin** [comment]
https://github.com/wangfenjin/simple/releases/tag/v0.0.3-alpha @am009 帮忙试一下这个 release 看还有问题没有

**Comment by wangfenjin** [comment]
> Sorry，最近有点忙，我今晚整理一下 PR 发上来，我们有复用您的项目代码，改动比较多，我需要单独抽离出来整理一下。

你们改动是包含了很多业务逻辑吗？如果是通用的可以考虑 commit 回来让其他人也能用上。

目前这个库我也加上了 release 的功能方便大家下载编译好的文件

**Comment by nmgwddj** [comment]
> > Sorry，最近有点忙，我今晚整理一下 PR 发上来，我们有复用您的项目代码，改动比较多，我需要单独抽离出来整理一下。
> 
> 你们改动是包含了很多业务逻辑吗？如果是通用的可以考虑 commit 回来让其他人也能用上。
> 
> 目前这个库我也加上了 release 的功能方便大家下载编译好的文件

主要改动是工程目录的调整、simple 改为静态库通过 sqlite3_auto_extension 加载、jieba 分词的不同分词逻辑接口暴露、iOS 编译的一些支持。
整体目录结构变化有些大，业务代码变化不大。我还是比较支持代码出自一处的维护方式，会考虑整体合并进来，但可能是分批次的。

**Comment by am009** [comment]
> https://github.com/wangfenjin/simple/releases/tag/v0.0.3-alpha @am009 帮忙试一下这个 release 看还有问题没有

感谢，没有问题了

**Comment by wangfenjin** [comment]
@nmgwddj  有需要的话可以给你加管理权限方便更新

iOS 和 Android 的自动编译我最近也在看，可能会加到编译流程里面

**Comment by wangfenjin** [comment]
我把这个 issue 关掉了，谢谢两位
