### ISSUE TITLE
已有数据表创建索引的问题

### ISSUE THREAD

**Issue by milandttp777** [wangfenjin/simple#58]
已经存在一个数据表data，里面有大量的数据，这个时候我再创建External Content Tables的fts表data_fts，data表里面以前的数据是没有索引存在在data_fts表里面的。根据（https://kimsereylam.com/sqlite/2020/03/06/full-text-search-with-sqlite.html）创建触发器也只是可以对以后的数据触发建索引，那么以前的数据我要建索引怎么办呢？因为以前的数据量比较大，再插入一次可能会比较耗时。

非常感谢

**Comment by wangfenjin** [comment]
这个好像没什么办法，你想搜索以前的数据就需要把他们导一遍

你把 fts 表和 trigger 创建好，然后在数据表执行一个 update 的操作让它触发 tigger，应该还好不会特别耗时
