### ISSUE TITLE
v0.0.3的libsimple-windows-x86.zip似乎是64位版

### ISSUE THREAD

**Issue by memoz** [wangfenjin/simple#59]
想在Windows上试一下，但是sqlite3的官网只提供了32位版命令行工具：https://www.sqlite.org/2021/sqlite-tools-win32-x86-3360000.zip

结果在.load simple的时候遇到“Error: %1 不是有效的 Win32 应用程序。”

用自己编译的64位版sqlite3可以加载。

**Comment by wangfenjin** [comment]
@memoz 谢谢反馈，帮忙测试一下这个 https://github.com/wangfenjin/simple/releases/download/v0.0.4-alpha/libsimple-windows-x86.zip x86 的版本，谢谢

**Comment by memoz** [comment]
不客气的。这个试了可以用。

**Comment by wangfenjin** [comment]
OK 我马上发布一个 0.0.4 版本
