### ISSUE TITLE
如何查询某个字段里面的指定内容

### ISSUE THREAD

**Issue by milandttp777** [wangfenjin/simple#61]
比如我的一个字段里面保存的是一个json字符串，{"content": "abcdefg", "text" : "abcdefg"}，我要查询"content"字段里面包含了abcd(但是不包含"text"字段里面的abcd)，这个该如何查询呢？
谢谢

**Comment by wangfenjin** [comment]
具体的需要等我周末有时间了做做实验。

其实这不是如何查询的问题，是如何插入数据的问题。大概的思路是需要看你怎么建 FTS 表，插入数据的时候把 json 数据解开，只插入你想搜索的数据。没有其他办法

**Comment by wangfenjin** [comment]
@milandttp777 下面是一个可以使用的方法：

```sql
-- content table
drop table if exists test;
create table test(value text);

-- index table
.load libsimple
drop table if exists t1;
CREATE VIRTUAL TABLE t1 USING fts5(x, tokenize = 'simple');

-- trigger to update index table, only insert the content key
-- you need enable json1 extension to use the json_extract() function
CREATE TRIGGER IF NOT EXISTS test_t1_i AFTER INSERT ON test BEGIN
  INSERT INTO t1(rowid, x) VALUES (new.rowid, json_extract(new.value, '$.content'));
END;
CREATE TRIGGER IF NOT EXISTS test_t1_d AFTER DELETE ON test BEGIN
  INSERT INTO t1(t1, rowid, x) VALUES('delete', old.rowid, json_extract(old.value, '$.content'));
END;
CREATE TRIGGER IF NOT EXISTS test_t1_u AFTER UPDATE ON test BEGIN
  INSERT INTO t1(t1, rowid, x) VALUES('delete', old.rowid, json_extract(old.value, '$.content'));
  INSERT INTO t1(rowid, x) VALUES (new.rowid, json_extract(new.value, '$.content'));
END;

-- insert data
insert into test values ('{"content": "命中", "text" : "出现在结果集"}');
insert into test values ('{"content": "不出现在结果集", "text" : "命中"}');

select 'all in test';
select rowid, * from test;

select '';
select 'match mz in content';
select test.rowid, test.* from test, t1 where t1.rowid=test.rowid and t1.x match simple_query('mz');
```

需要注意的是：
1. 哪些能搜索哪些不能，完全是由你把什么数据放到 fts 表里面决定的，放到 fts 表里的数据就能搜索。如果你只想搜索 content，那就像上面的例子那样，你只能把 content 里面的内容 json_extract 出来放进去
2. 所以如果你有时候想搜索 content，有时候又想搜索 text，那你就需要把这个 json 解析成两个字段，然后通过类似 t1.x 或者 t1.y 这样来根据需求 match

**Comment by milandttp777** [comment]
非常感谢！
我现在的做法就是这样做的，就是看能不能直接用查询来做更简单一点

**Comment by wangfenjin** [comment]
只有这个办法

**Comment by yugaoxiang** [comment]
@wangfenjin 你好，看上面的例子`select test.rowid, test.* from test, t1 where t1.rowid=test.rowid and t1.x match simple_query('mz');`可以两个表一起查1.我这边测试的时候发现两个表分别两条数据，会查出来4条，不知道是怎么回事？2.如果我加上left join 之类的语句就会提示没有找到match的方法。3.fts5可以插入二进制（blob）吗？我这边有一张表id是二进制类型的，插入的时候有时候失败有时候成功，所以我把它转成16进制字符串了。如果不能两个表一起查，拿到id之后，不知道怎么去业务表里查了。where in好像只能用字符串

**Comment by wangfenjin** [comment]
@yugaoxiang 
1. 不会啊，我拿上面的 SQL 跑没问题。你可以把你完整的 SQL 贴出来
2. 你需要改写你的 query https://stackoverflow.com/a/44174949/1203241
3. 理论上如果你把你说的这个 id 字段标记成 UNINDEXED，是可以插入任意的二进制的，但是我没试过
