### ISSUE TITLE
使用node-sqlite3加载的报错问题

### ISSUE THREAD

**Issue by zhengtulymGh** [wangfenjin/simple#64]
node-sqlite3里面的loadExtension函数对加载的插件有编译版本要求，请问这个版本指的是什么呢？
[https://github.com/mapbox/node-sqlite3/wiki/Extensions](https://github.com/mapbox/node-sqlite3/wiki/Extensions)
Note: Make sure that the extensions you load are compiled or linked against the same version as node-sqlite3 was compiled. Version mismatches can lead to unpredictable behavior.

**Comment by wangfenjin** [comment]
你是在什么操作系统？在 node 里面肯定是可以用的

https://github.com/netease-kit/Kit-FullSearch-Electron/blob/main/src/index.ts#L131 这个是网易开源的一个在 node 使用的例子

https://github.com/wangfenjin/simple/pull/67 这是我正在验证的一个更简单的例子，目前我自己验证只有 windows 还有点问题，但是我没有 windows 电脑所以不太好调试

**Comment by wangfenjin** [comment]
https://github.com/mapbox/node-sqlite3/issues/1418 windows 下面我怀疑是 node-sqlite3 自己有点问题，但是我没有 windows 电脑没法验证；就像你说的

>>但是这个dll插件用sqlite broswer工具直接加载又可以正常使用

**Comment by wangfenjin** [comment]
看我给的例子吧，大概率是你指定的目录不对

**Comment by wangfenjin** [comment]
@zhengtulymGh 看了一下你的报错信息，load 拓展的时候指定 libsimple 就行，别加 libsimple.dylib 。你看你的错误信息里面文件名后缀出现了两次

**Comment by nmgwddj** [comment]
> 版本的问题好像确实不是问题，编译的sqlite版本改为了和node-sqlite3 最新版 5.0.2一致的的3.36.0仍然有问题 主要异常有两个 1、加载插件后创建的虚拟表是空的，没有字段 2、在真实表插入数据会提示 toknizer: simple不存在
> 
> 但是这个dll插件用sqlite broswer工具直接加载又可以正常使用，只是用node-sqlite的loadExtension加载不行

打开数据库后，先 LoadExtension、再创建表或执行查询插入操作，否则会报错无法找到 simple 扩展。

**Comment by zhengtulymGh** [comment]
> > 试了下mac下的插件，编译后在build/run/src下面找到个libsimple.dylib文件，用node-sqlite3里面的loadExtension加载后没能创建成功虚拟表，用sqlite broswer工具加载报错
> > ```
> > 加载扩展时出错: dlopen(******/libsimple.dylib.dylib, 10): image not found
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 直接使用编译好的也会报这个错 https://github.com/wangfenjin/simple/releases 这个是什么问题呢？
> 
> sqlite broswer 主干版本有 bug，用他的 nightly 版本。他们代码在加载扩展的时候多追加了后缀名。

好的，感谢。我去试一下

**Comment by wangfenjin** [comment]
有问题欢迎继续讨论

**Comment by baolong** [comment]
同样遇到这个问题，折腾了好久，终于解决了。

我自己的解决办法是：安装Microsoft Visual C++运行库

地址：https://visualstudio.microsoft.com/zh-hans/downloads/
![image](https://github.com/wangfenjin/simple/assets/2135276/2a54fbe1-0ae2-495f-9920-c08d815e2fd0)
