### ISSUE TITLE
请问dict里的数据可以跨平台公用吗

### ISSUE THREAD

**Issue by LeeSanity** [wangfenjin/simple#71]
打包节省一些空间

**Comment by wangfenjin** [comment]
可以吧，就是普通的文本

**Comment by LeeSanity** [comment]
another question: 
create virtual table t using fts5(a, b, c), 可以通过simple_query指定仅匹配b，c两个column吗

**Comment by wangfenjin** [comment]
可以

select * from t where b match simple_query('123') or c match imple_query('123')

**Comment by wangfenjin** [comment]
simple_query 是一个普通的函数，只要 sql 是合法的怎么用都行

**Comment by LeeSanity** [comment]
这样用会报错，感觉有点奇怪
![image](https://user-images.githubusercontent.com/13415260/143000128-4686d134-5251-4efb-9c1e-a6dc64e2e291.png)

**Comment by wangfenjin** [comment]
把你的建表语句插入数据的方法查询都发出来，不然没法给你查
