### ISSUE TITLE
/lib64/libm.so.6: version `GLIBC_2.29' not found (required by libsimple.so)

### ISSUE THREAD

**Issue by ixuuux** [wangfenjin/simple#72]
centos7加载扩展时（在 https://github.com/wangfenjin/simple/releases/tag/v0.1.0 下载），出现GLIBC版本不匹配。
执行 ```strings /lib64/libc.so.6 | grep GLIBC_2``` 后发现最高版本只有2.17。
本来是该升级版本的，但是我怕出现什么问题，所以来到这里求助，万分感谢。

**Comment by wangfenjin** [comment]
要么你升级机器上的 glibc 版本，要么你在你的机器上自己编译。

理论上这个库对 libc 版本没要求，release 里面的是在 CI 里打包的，github CI 机器上是什么版本链接的时候就是什么版本

**Comment by ixuuux** [comment]
谢谢，通过本机编译解决了这个问题

**Comment by jiakuan** [comment]
在Ubuntu 16.04 上遇到类似问题，手动编译libsimple就可以了。
