### ISSUE TITLE
iOS上执行sqlite3_simple_init报错

### ISSUE THREAD

**Issue by milandttp777** [wangfenjin/simple#75]
rc = sqlite3_prepare(db, "SELECT fts5(?1)", -1, &pStmt, 0);
iOS平台上执行到这一句语句的时候报错，返回值SQLITE_ERROR，错误信息（wrong number of arguments to function fts5()）

**Comment by wangfenjin** [comment]
参考 #73 #74

**Comment by milandttp777** [comment]
我的sqlite版本是3.15.2，而且是直接编译的sqlite.c的源代码，编译选项也有SQLITE_ENABLE_FTS5

**Comment by wangfenjin** [comment]
你可以先不加载这个插件，直接用自带的分词器试试支不支持fts5

**Comment by wangfenjin** [comment]
有问题欢迎继续讨论
