### ISSUE TITLE
sql问题

### ISSUE THREAD

**Issue by yugaoxiang** [wangfenjin/simple#77]
当我使用`@"CREATE VIRTUAL TABLE IF NOT EXISTS 't_person' USING fts5(age INTEGER, name TEXT, id Blob PRIMARY KEY,  tokenize='simple')"`创建表的时候，提示`Error calling sqlite3_step (1: unrecognized column option: INTEGER) SQLITE_ERROR`
我必须把类型去掉才能创建成功，去掉类型保留主建也不可以

**Comment by wangfenjin** [comment]
这个跟扩展没关系，这是 sqlite fts 本身的语法限制决定的 https://www.sqlite.org/fts5.html 
> It is an error to add types, constraints or [PRIMARY KEY](https://www.sqlite.org/lang_createtable.html#primkeyconst) declarations to a CREATE VIRTUAL TABLE statement used to create an FTS5 table.

一般只往 fts 表里放需要搜索的数据，具体怎么使用可以看看我这篇文章 https://www.wangfenjin.com/posts/simple-jieba-tokenizer/#%E4%BD%BF%E7%94%A8
