### ISSUE TITLE
是否可以release一下arm64的包

### ISSUE THREAD

**Issue by daqi** [wangfenjin/simple#78]

**Comment by wangfenjin** [comment]
你指的是哪个系统？

**Comment by daqi** [comment]
linux的






------------------ 原始邮件 ------------------
发件人: Wang Fenjin ***@***.***&gt;
发送时间: 2022年3月21日 18:52
收件人: wangfenjin/simple ***@***.***&gt;
抄送: 大齐 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [wangfenjin/simple] 是否可以release一下arm64的包 (Issue #78)

**Comment by wangfenjin** [comment]
@daqi 可以试下 https://github.com/wangfenjin/simple/releases/tag/v0.2.0-alpha 这里的包，aarch64 的那个，系统旧就选  gcc-7 那个

**Comment by eattopking** [comment]
是否可以release 一下macos 和windows 的arm64的包

**Comment by wangfenjin** [comment]
macos 是支持的； Windows 不太熟，欢迎 PR

**Comment by daqi** [comment]
> macos 是支持的； Windows 不太熟，欢迎 PR

macos arm64已经支持了吗？

**Comment by wangfenjin** [comment]
macos 的编译输出应该是通用的，你可以试试

**Comment by daqi** [comment]
ok，感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wang Fenjin ***@***.***&gt;
发送时间: 2022年4月2日 18:39
收件人: wangfenjin/simple ***@***.***&gt;
抄送: 大齐 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [wangfenjin/simple] 是否可以release一下arm64的包 (Issue #78)






macos 的编译输出应该是通用的，你可以试试
