### ISSUE TITLE
怎么编译出 iOS 可用的动态库

### ISSUE THREAD

**Issue by lazyun** [wangfenjin/simple#79]
你好，我的项目使用 golang 做的。go 版本的 sqlite 并没有提供 sqlite3_auto_extension 这个静态库加载的函数，只提供了使用动态库加载的方法。我尝试了下并没有编译出动态库。想问下你这边有什么方案么？

**Comment by wangfenjin** [comment]
我写了一个 go 的例子 #80 可以用啊

你的标题是 iOS 跟 go 有什么关系

**Comment by wangfenjin** [comment]
有问题再讨论

**Comment by lazyun** [comment]
我使用 go 生成 framework 提供给 iOS 端使用。但是现在没编译出 iOS 可用的动态库。go 版本的 sqlite 没有 #73 中加载静态库的方法。

**Comment by wangfenjin** [comment]
可以给 go 的库提需求让他们加上加载静态库的方法
