### ISSUE TITLE
make命令如何指定CPU架构

### ISSUE THREAD

**Issue by zrina1314** [wangfenjin/simple#8]
Android 的常用CPU 架构有 : armeabi / armeabi-v7a / arm64-v8a / x86 / x86_64 /MIPS / MIPS64
想要指定输出  armeabi / armeabi-v7a / arm64-v8a 这三种的SO库，要怎么弄
      --- 不会弄 C C++

**Comment by zrina1314** [comment]
使用Mac 编译出来的 so 是x86-64的 CPU 架构，移动端Android 或IOS 貌似用不了

libsimple.so：     文件格式 mach-o-x86-64
libsimple.so
体系结构：i386:x86-64，标志 0x00000050：
HAS_SYMS, DYNAMIC
起始地址 0x0000000000000000
 MACH-O header:
   magic:      0xfeedfacf
   cputype:    0x1000007 (X86_64)
   cpusubtype: 0x3 (X86_ALL)
   filetype:   0x6
   ncmds:      0xf
   sizeocmds:  0x6c0
   flags:      0x118085
   version:    2

**Comment by wangfenjin** [comment]
统一在 #2 讨论吧
