### ISSUE TITLE
better-sqlite3 加载扩展报错：找不到指定的模块

### ISSUE THREAD

**Issue by legendhl** [wangfenjin/simple#81]
better-sqlite3版本号：7.4.3
simple版本：0.1.0
simple.dll路径正确，文件存在，但是执行loadExtension就会报错：找不到指定的模块
是现在不太支持better-sqlite3吗

**Comment by legendhl** [comment]
mac会报这样的错
dlopen(/Applications/test.app/Contents/Resources/build/sqlite3-fts5/libsimple.dylib, 10): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/test.app/Contents/Resources/build/sqlite3-fts5/libsimple.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/test.app/Contents/Resources: SqliteError: dlopen(/Applications/test.app/Contents/Resources/build/sqlite3-fts5/libsimple.dylib, 10): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/test.app/Contents/Resources/build/sqlite3-fts5/libsimple.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/test.app/Contents/Resources
    at Database.loadExtension (/Applications/test.app/Contents/Resources/app.asar/node_modules/better-sqlite3/lib/methods/wrappers.js:19:14)
    at Object.originCreate (/Applications/test.app/Contents/Resources/app.asar/dist/server.js:1:319401)
    at async Object.create (/Applications/test.app/Contents/Resources/app.asar/dist/server.js:1:320161)
    at async /Applications/test.app/Contents/Resources/app.asar/dist/server.js:1:3827

**Comment by wangfenjin** [comment]
你操作系统是不是比较旧，如果你下载我 release 的包它是针对新系统的 

类似的问题 https://github.com/nodegui/nodegui/issues/391

**Comment by wangfenjin** [comment]
“找不到指定的模块” 感觉是你的路径没设置对吧

**Comment by legendhl** [comment]
> 

路径是正确的，对应的扩展文件也确实存在（windows下simple.dll，mac下libsimple.dylib）

**Comment by legendhl** [comment]
> “找不到指定的模块” 感觉是你的路径没设置对吧

路径是正确的，对应的扩展文件也确实存在（windows下simple.dll，mac下libsimple.dylib）

**Comment by wangfenjin** [comment]
文件存在不代表他能找到，你需要检查它去哪些目录搜索了 dll，我没用 windows，或者看看写绝对路径能不能行

**Comment by wangfenjin** [comment]
你可以把路径打出来证明它确实去你的路径读了

**Comment by legendhl** [comment]
> 文件存在不代表他能找到，你需要检查它去哪些目录搜索了 dll，我没用 windows，或者看看写绝对路径能不能行

db.loadExtension(simpleFilePath);
就是用的绝对地址，这里的simpleFilePath就是绝对地址

**Comment by wangfenjin** [comment]
> > 文件存在不代表他能找到，你需要检查它去哪些目录搜索了 dll，我没用 windows，或者看看写绝对路径能不能行
> 
> db.loadExtension(simpleFilePath); 就是用的绝对地址，这里的simpleFilePath就是绝对地址

去掉后面的 .dll 试试，有些库会自动加拓展的后缀，比如 dll, so 什么的

**Comment by wangfenjin** [comment]
https://www.sqlite.org/loadext.html
> Note that different operating systems use different filename suffixes for their shared libraries. Windows uses ".dll", Mac uses ".dylib", and most unixes other than mac use ".so". If you want to make your code portable, you can omit the suffix from the shared library filename and the appropriate suffix will be added automatically by the [sqlite3_load_extension()](https://www.sqlite.org/c3ref/load_extension.html) interface.

**Comment by wangfenjin** [comment]
@legendhl 对于 mac 的问题，试下 https://github.com/wangfenjin/simple/releases/tag/v0.2.0-alpha 这里的包
