### ISSUE TITLE
拼音匹配问题

### ISSUE THREAD

**Issue by sjtusyl** [wangfenjin/simple#85]
simple_query('tt') 
为啥可以匹配‘王超超’

**Comment by sjtusyl** [comment]
找到了 超 居然是个多音字。。。。
chāo,chǎo,chào,tiào  # 超

**Comment by wangfenjin** [comment]
如果不想要，可以自己改一下 pinyin.txt 然后重新编译

**Comment by sjtusyl** [comment]
这个pinyin文件太全了，导致有的字有很多平时用不到的发音，简拼搜索的时候有干扰

**Comment by wangfenjin** [comment]
同意，所以最好还是自己根据需求在这个基础上做简化
