### ISSUE TITLE
windows 编译问题

### ISSUE THREAD

**Issue by sjtusyl** [wangfenjin/simple#86]
我在windows上编译simple的时候遇到个问题，我的电脑连不上网；
我就手动下了个 release-1.10.0.zip文件在编译目录下；
但是 文件hash校验一直不过，还是会重新下载；
请教下作者，有什么办法可以规避么

**Comment by wangfenjin** [comment]
https://github.com/wangfenjin/simple/archive/refs/tags/v0.2.0.zip 是说这个文件下载不下来？

**Comment by sjtusyl** [comment]
> 这个 https://github.com/google/googletest/archive/release-1.10.0.zip

**Comment by wangfenjin** [comment]
```
mkdir build
cd build
cmake ..  -DCMAKE_BUILD_TYPE=Release -DCODE_COVERAGE=OFF -DBUILD_SHELL=OFF -DBUILD_TEST_EXAMPLE=OFF -DSIMPLE_WITH_JIEBA=OFF
make
```

这样编译的时候就不会下载任何文件

**Comment by sjtusyl** [comment]
还是会下载googletest，是不是CMakeLists要做些修改呢

**Comment by wangfenjin** [comment]
不会啊，你把目录清空重新编译

**Comment by sjtusyl** [comment]
嗯嗯 Cmake阶段可以
make阶段没有makefile
make: *** No targets specified and no makefile found.  Stop.

**Comment by wangfenjin** [comment]
不要再来问这种问题了，我完整的命令都放出来了

**Comment by sjtusyl** [comment]
好的 我再看看 感谢
