### ISSUE TITLE
simple_query 是否可以通过搜英文单词的一部分搜索到内容

### ISSUE THREAD

**Issue by eattopking** [wangfenjin/simple#88]

**Comment by eattopking** [comment]
例如单词learn, 搜索ar想到包含learn的内容, 现在测试只能从头开始能搜到, 比如搜le可以搜到包含learn的内容

**Comment by wangfenjin** [comment]
不行，现在做的都是前缀匹配。你需要考虑你的需求本身是否合理，你说的这个理论上不具有通用性，不适合放到我这个库实现。

如果真要做可以自己拼装 query，simple_query 可以理解成只是一个函数，传入一个 string，输出一个 string；这个函数你放到自己的应用程序去写也是可以的

**Comment by kongfu-cat** [comment]
> 不行，现在做的都是前缀匹配。你需要考虑你的需求本身是否合理，你说的这个理论上不具有通用性，不适合放到我这个库实现。
> 
> 如果真要做可以自己拼装 query，simple_query 可以理解成只是一个函数，传入一个 string，输出一个 string；这个函数你放到自己的应用程序去写也是可以的

你好, 想了解下为什么采用前缀匹配. 是因为拼音查找吗? 如果需求场景不涉及拼音查找, 是否理论上可以放开前缀匹配?
前缀匹配和正常的短语匹配性能在 sqlite-fts5 中差异大吗?

**Comment by wangfenjin** [comment]
啥叫“正常的短语匹配”啊，你可能理解错了我们讨论的内容。

比如文本是 "hello"，搜索 "he" 能命中 “hello” 叫前缀匹配，搜索 “el” 或者 “lo” 也能（这个库不能，因为不符合直觉！）搜到 “hello”就是非前缀匹配。

性能高低看你怎么建索引，如果你搜索 “lo” 也想搜到 “hello”，那你就要建对应的索引，性能就不会有影响，但是这个会导致索引文件很大

**Comment by wangfenjin** [comment]
非前缀匹配是在 SQL 里表现类似 like "%abc%"，这是不符合普通用户直觉的
