### ISSUE TITLE
macos系统编译后分发，其它mac使用报错

### ISSUE THREAD

**Issue by china-net-meng** [wangfenjin/simple#9]
你好，报错如下，开发环境mac os 11，使用环境mac os 10
<img width="565" alt="WechatIMG294" src="https://user-images.githubusercontent.com/33045952/102854618-d5876680-445d-11eb-9666-d6cbafbb301f.png">

**Comment by wangfenjin** [comment]
看起来不是 libsimple 的问题，是 sqlite3-shell 不能在低版本机器上运行。你看看 osx10 机器上有 sqlite3 吗？如果有直接用 `sqlite3 < test.sql` 试试

**Comment by china-net-meng** [comment]
你好，用系统自带的sqlite3(mac osx 11)没有.load方法，应该是编译时没有开启此功能，如下：
sqlite3 < test.sql
Error: unknown command or invalid arguments:  "load". Enter ".help" for help
Error: near line 7: no such tokenizer: simple
Error: near line 10: no such table: t1
所有数据:
Error: near line 13: no such table: t1
搜索 杰伦:
Error: near line 16: no such table: t1
搜索 zhoujiel:
Error: near line 19: no such table: t1
搜索 zjl:
Error: near line 22: no such table: t1
搜索 ZHOUJi:
Error: near line 25: no such table: t1
搜索 love zg:
Error: near line 28: no such table: t1

**Comment by china-net-meng** [comment]
感觉不是sqlite3-shell的问题，因为我同时使用之前提到的方法，
也就是使用
./configure CPPFLAGS="-DSQLITE_ENABLE_ICU `icu-config --cppflags`" LDFLAGS="`icu-config --ldflags`"
make
编译了带有icu分词功能的sqlite3，分发到osx10上面报错找不到icu.lib，也就是说明我在osx11上编译的程序在osx10上是可以运行的，如下
<img width="545" alt="WechatIMG291" src="https://user-images.githubusercontent.com/33045952/102855369-7de9fa80-445f-11eb-8671-ddb5dc1ee969.png">

**Comment by wangfenjin** [comment]
嗯，那你需要在osx10 上编译一个支持 fts5 的 sqlite binary 才行，这个问题不在我们能解决的范围内

**Comment by china-net-meng** [comment]
你好，我确定了，确实是lib的问题，单独执行sqlite3可以，在里面加载.load libsimple就报错了，如下
<img width="565" alt="WechatIMG294" src="https://user-images.githubusercontent.com/33045952/102855947-9b6b9400-4460-11eb-805e-6c635c0f8e6d.png">

**Comment by wangfenjin** [comment]
感觉还是得在低版本电脑上编译才行

**Comment by china-net-meng** [comment]
你好，了解，如果我想要把libsimple库编译进sqlite3该如何操作呢？不以外部动态库的形式，而是编译进二进制程序，这样可行吗？怎么操作？

**Comment by wangfenjin** [comment]
${CPP} -mmacosx-version-min=10.9 -std=c++14 src/*.c src/*.cc -shared -rdynamic -o ${LIBNAME} -I build/ -fPIC ${LIB} ${SHELL_FLAGS}

你把 Makefile 里面改一下，加上 -mmacosx-version-min=10.9  再编译试试，然后 copy 到低版本看能不能 run

**Comment by wangfenjin** [comment]
> 你好，了解，如果我想要把libsimple库编译进sqlite3该如何操作呢？不以外部动态库的形式，而是编译进二进制程序，这样可行吗？怎么操作？

不建议这么搞，那你需要自己改 sqlite3 的代码了，这样维护会是问题。

另外就是你这么搞了，你也要解决 sqlite3 编译完在低版本跑的问题，所以并不解决什么

**Comment by china-net-meng** [comment]
你好加上 -mmacosx-version-min=10.9也是不行，但是我发现，从osx10编译后，分发到osx11上是可以执行的。谢谢啦

**Comment by china-net-meng** [comment]
你好，我又发现了一个问题，osx11和osx10编译出的lib有所不同，这是不是就是导致的原因？如下
------------osx10编译的
otool -L libsimple.dylib
libsimple.dylib:
	libsimple.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
------------osx11编译的
otool -L libsimple.dylib
libsimple.dylib:
	libsimple.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)

**Comment by china-net-meng** [comment]
> 你好，我又发现了一个问题，osx11和osx10编译出的lib有所不同，这是不是就是导致的原因？如下
> ------------osx10编译的
> otool -L libsimple.dylib
> libsimple.dylib:
> libsimple.dylib (compatibility version 0.0.0, current version 0.0.0)
> /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
> /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
> ------------osx11编译的
> otool -L libsimple.dylib
> libsimple.dylib:
> libsimple.dylib (compatibility version 0.0.0, current version 0.0.0)
> /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
> /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)

libSystem.B.dylib是系统自带的库对吧？请问如何在编译时指定其版本？

**Comment by wangfenjin** [comment]
这个是系统库，没法指定版本吧；可能高版本的兼容了低版本，所以你在 10 编译的 11 能用
