### ISSUE TITLE
接入GRDB库的问题

### ISSUE THREAD

**Issue by bruceFighting** [wangfenjin/simple#91]
大佬有没有接入GRDB库的例子，按照你这个流程无从下手，从demo下载编译文件也是一大堆错误，有点懵逼（C++小白）

**Comment by wangfenjin** [comment]
不好意思我不太懂iOS，你可以参考 #73

**Comment by bruceFighting** [comment]
> 不好意思我不太懂iOS，你可以参考 #73
<img width="1825" alt="WeChat8156b14b3a97ca5acb3e9b10e72eb3d5" src="https://user-images.githubusercontent.com/19966020/172391867-769e7dba-fefd-417f-88e5-6d14c000e444.png">
这个错误是哪个库的

**Comment by wangfenjin** [comment]
这个库的；你编译流程有问题

这个库里有很多文档你看看吧

**Comment by fakerlogic** [comment]
> 大佬有没有接入GRDB库的例子，按照你这个流程无从下手，从demo下载编译文件也是一大堆错误，有点懵逼（C++小白）

引入.a文件，然后注册组件，最后grdb create fts的时候指定这个组件 t.tokenizer = FTS5TokenizerDescriptor(components: ["simple"]) 就可以

**Comment by fakerlogic** [comment]
> 这个库的；你编译流程有问题
> 
> 这个库里有很多文档你看看吧
您好：
    我在使用sqlite过程中，使用了fts功能，然后加载了fts5 的simple扩展，然后发现那张fts表里面没有数据，column有没有，但是能正常搜索到数据。如果用正常的自带的tokenizer，例如porter, fts那张表里面都是有数据的。不知道我是缺失什么步骤还是什么原因。
    感谢！期待您的回复。

**Comment by wangfenjin** [comment]
需要把你建表和插入数据的 SQL 我看下；理论上 simple 和 porter 这些没有区别，如果你只是改了 tokenizer 但是数据不一样，不太可能

**Comment by fakerlogic** [comment]
> 需要把你建表和插入数据的 SQL 我看下；理论上 simple 和 porter 这些没有区别，如果你只是改了 tokenizer 但是数据不一样，不太可能

try db.create(table: "ADDRESSBOOK") { t in
                t.column("id", .integer).primaryKey(onConflict: .replace, autoincrement: true)
                t.column("user_id", .text).unique(onConflict: .replace).indexed().notNull()
                t.column("pid", .text).notNull()
                t.column("label", .text).notNull()
                t.column("pinyin", .text)
                t.column("login_name", .text).notNull()
                t.column("mobile", .text)
                t.column("email", .text)
                t.column("portrait", .text)
                t.column("abbrev", .text)
                t.column("is_resign", .boolean).defaults(to: false)
                t.column("is_master", .boolean).defaults(to: false)
                t.column("remarks", .text)
                t.column("desc", .text)
                t.column("flag", .text).defaults(to: "Y")
            }

//            try db.execute(sql: """
//                CREATE VIRTUAL TABLE ADDRESSBOOK_FTS USING fts5 (
//                    label,
//                    pinyin,
//                    email,
//                    abbrev,
//                    remarks,
//                    desc,
//                    content=ADDRESSBOOK,
//                    content_rowid=id,
//                    tokenize='simple'
//                )
//                """)
            
            try db.create(virtualTable: "ADDRESSBOOK_FTS", using: FTS5()) { t in
                t.column("label")
                t.column("pinyin")
                t.column("email")
                t.column("abbrev")
                t.column("remarks")
                t.column("desc")
//                t.content = "ADDRESSBOOK"
//                t.contentRowID = "ADDRESSBOOK.id"
                t.synchronize(withTable: "ADDRESSBOOK")
                t.tokenizer = FTS5TokenizerDescriptor(components: ["simple"])
            }

我是用的grdb，第二部分注释的是raw sql创建的fts，第三部分是grdb创建的fts，这样写tokenize创建出的fts表没有内容，但是正常搜索

**Comment by wangfenjin** [comment]
你用的是 https://www.sqlite.org/fts5.html#external_content_tables 这个，理论上内容就是不会存在fts 表里面

也不能直接往 fts 表里面插入数据，而要通过上面链接中提到的 trigger 来保持数据同步

**Comment by fakerlogic** [comment]
> 你用的是 https://www.sqlite.org/fts5.html#external_content_tables 这个，理论上内容就是不会存在fts 表里面
> 
> 也不能直接往 fts 表里面插入数据，而要通过上面链接中提到的 trigger 来保持数据同步

好的，感觉有点奇怪，我用的自带的，fts表里面是可以看到东西的[破涕为笑]

**Comment by wangfenjin** [comment]
看 fts 表建的是哪种类型。你现在的用法是比较推荐的用法，只要记得配置好 trigger 就好

**Comment by wangfenjin** [comment]
如果你的项目也是开源的，做好了可以分享一下，让其他 iOS 的人也能学习

**Comment by fakerlogic** [comment]
> 如果你的项目也是开源的，做好了可以分享一下，让其他 iOS 的人也能学习

公司的项目，接入grdb基本就是上面那些了，加上本工程下的两个静态库和oc文件，就可以了，很方便使用，trigger grdb已经封装好了；
我们用的也是 External Content Tables，正常用分词器，fts表里是能够查看column和同步的内容的，用了simple就不行，但是搜索啥的都是正常

**Comment by EnjoyWT** [comment]
@fakerlogic  可以问下，GRDB.swift 中如何使用这个库的吗， 
1. 如何注册这个库？
2. 查询时是和普通的 external_content_tables 一样吗

**Comment by EnjoyWT** [comment]
1. 关于问题1 如何注册这个库的意思是：如何自定义这个分词器时使用这个.a的库。
2. 查询时，如何使用

**Comment by Fr3027** [comment]
> 1. 关于问题1 如何注册这个库的意思是：如何自定义这个分词器时使用这个.a的库。
> 2. 查询时，如何使用

大佬，我在GRDB库看到您提的帖子了，也有相同的问题，请问您解决了吗？

**Comment by wangfenjin** [comment]
readme 里面有好几个 iOS 的例子，建议研究一下

**Comment by Fr3027** [comment]
> readme 里面有好几个 iOS 的例子，建议研究一下

大佬您好，我研究了一下午，发现这个库是依赖于sqlite3_auto_extension函数的，但是GRDB自带的sqlite不支持，所以很好奇@fakerlogic 是通过什么方法成功运行的

**Comment by Fr3027** [comment]
> > readme 里面有好几个 iOS 的例子，建议研究一下
> 
> 大佬您好，我研究了一下午，发现这个库是依赖于sqlite3_auto_extension函数的，但是GRDB自带的sqlite不支持，所以很好奇[@fakerlogic](https://github.com/fakerlogic) 是通过什么方法成功运行的

这个库和GRDB库的相关issue 我几乎都爬遍了，没找到解决办法😭

**Comment by Fr3027** [comment]
GRDB库对应的issue：https://github.com/groue/GRDB.swift/issues/1458

**Comment by wangfenjin** [comment]
https://github.com/groue/GRDB.swift/blob/master/Documentation/CustomSQLiteBuilds.md

@Fr3027 我看作者已经回复的很清楚了，根据这个文档编译自己的 sqlite，把 FTS5 那个选项打开就可以

**Comment by wangfenjin** [comment]
那个 issue 大概的意思是，GRDB 默认用系统自带的 sqlite，而自带的不支持 fts5；如果你想支持，需要根据那个文档编译；如果他的文档写的不对你可以反馈

**Comment by wangfenjin** [comment]
都是写代码的人，多研究研究吧

**Comment by Fr3027** [comment]
> https://github.com/groue/GRDB.swift/blob/master/Documentation/CustomSQLiteBuilds.md
> 
> [@Fr3027](https://github.com/Fr3027) 我看作者已经回复的很清楚了，根据这个文档编译自己的 sqlite，把 FTS5 那个选项打开就可以



> 那个 issue 大概的意思是，GRDB 默认用系统自带的 sqlite，而自带的不支持 fts5；如果你想支持，需要根据那个文档编译；如果他的文档写的不对你可以反馈

好的谢谢大佬回复，感觉像是自带版本把sqlite3_auto_extension给禁用掉了的原因，我再自己编译一个试试 看能解决这问题不

**Comment by wangfenjin** [comment]
@Fr3027 解决了吗

**Comment by Fr3027** [comment]
> [@Fr3027](https://github.com/Fr3027) 解决了吗

解决了大佬。后来我自己编译了GRDB可以用了，但我有些担心不用系统自带的sqlite以后会有其他问题。于是我换成了提前录入分词结果的方案，没使用这个库。
